# Number of NumPy approaches for creating an object of ndarray

## In Python programming, we have number of approaches for creating an object of ndarray.
## Some essential approaches for creating an object of ndarray are:
### a) array()
### b) range()
### c) zeros()
### d) ones()
### e) full()
### f) linspace()
### g) eye()
### h) identity()
### i) hstack()
### j) vstack()
### k) numpy.random
#### 1) randint()
#### 2) randn()
#### 3) normal()
#### 4) rand()
#### 5) uniform()
#### 6) shuffle()
## Note: Here ndarray is a pre-defined class present in numpy module.

# a) array()
## syntax: varname = numpy.array(object,dtype) #obj=int,float,complex,bool
## This function is used for converting traditional python object into ndarray object.

In [1]:
import numpy as np

In [2]:
b = 100
print(b,type(b),id(b))
print("---------------------")
a = np.array(b)
print(a,type(a),id(a))

100 <class 'int'> 140725240184840
---------------------
100 <class 'numpy.ndarray'> 1797881644496


In [3]:
c = 2.3
print(c,type(c),id(c))
print("-------------------------------")
d = np.array(c)
print(d,type(d),id(d))

2.3 <class 'float'> 1797922960048
-------------------------------
2.3 <class 'numpy.ndarray'> 1797920892720


In [4]:
c = 5.3
print(c,type(c),id(c))
print("-------------------------------")
d = np.array(c)
print(d,type(d),id(d))
print("-------------------------------")
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)

5.3 <class 'float'> 1797918669328
-------------------------------
5.3 <class 'numpy.ndarray'> 1797923653840
-------------------------------
0
()
1
float64


In [6]:
b = 100
print(b,type(b),id(b))
print("---------------------")
a = np.array(b)
print(a,type(a),id(a))
print("---------------------")
print("Dimensions=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal data-type=",a.dtype)

100 <class 'int'> 140725240184840
---------------------
100 <class 'numpy.ndarray'> 1797923653648
---------------------
Dimensions= 0
Shape= ()
Size= 1
Internal data-type= int64


# b) range()

In [7]:
r = range(10)
print(r,type(r),id(r))

range(0, 10) <class 'range'> 1797897106464


In [8]:
for val in r:
    print(val,end="\t")

0	1	2	3	4	5	6	7	8	9	

In [9]:
for val in r:
    print(val,end="\n")

0
1
2
3
4
5
6
7
8
9


In [11]:
for val in range(0,15):
    print(val,end="\t")

0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	

In [12]:
for val in range(0,21,2):
    print(val,end="\t")

0	2	4	6	8	10	12	14	16	18	20	

In [16]:
r = range(10,61,2)
print(r,type(r),id(r))
print("-------------------------------------------------")
a = np.array(r)
print(a,type(a),id(a))
print("-------------------------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

range(10, 61, 2) <class 'range'> 1797920111328
-------------------------------------------------
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60] <class 'numpy.ndarray'> 1797938563184
-------------------------------------------------
Dimensional= 1
Shape= (26,)
Size= 26
Internal datatype= int64


## Now, I want to re-shape the 1D into 2D array.
## To reshape the ndarray object we can use
## 1) shape() 2) reshape()
## syntax: ndarrayobj.shape(row,cal) or ndarrayobj.reshape(row,cal)

In [18]:
a = range(100,156,5)
print(a,type(a),id(a))
print("---------------------------------------------")
b = np.array(a)
print(b,type(b))
print("-------------------------------------------------")
print("Dimensional=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal datatype=",b.dtype)

range(100, 156, 5) <class 'range'> 1797899174368
---------------------------------------------
[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
-------------------------------------------------
Dimensional= 1
Shape= (12,)
Size= 12
Internal datatype= int64


In [23]:
b.shape = (4,3)
print("----------------------")
print(b,type(b))
print("----------------------")
print("Dimensional=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal datatype=",b.dtype)

----------------------
[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
----------------------
Dimensional= 2
Shape= (4, 3)
Size= 12
Internal datatype= int64


In [24]:
x = range(0,16)
print(x,type(x))
print("--------------------------")
y = np.array(x)
print(y,type(y))
print("---------------------------")
print("Dimensional=",y.ndim)
print("Shape=",y.shape)
print("Size=",y.size)
print("Internal datatype=",y.dtype)

range(0, 16) <class 'range'>
--------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>
---------------------------
Dimensional= 1
Shape= (16,)
Size= 16
Internal datatype= int64


In [25]:
y.shape = (4,4)
print(y,type(y))
print("-------------------")
print("Dimensional=",y.ndim)
print("Shape=",y.shape)
print("Size=",y.size)
print("Internal datatype=",y.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
-------------------
Dimensional= 2
Shape= (4, 4)
Size= 16
Internal datatype= int64


In [29]:
x = y.reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [30]:
x = y.reshape(8,2)
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [31]:
x = y.reshape(2,8)
print(x)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [32]:
x = y.reshape(16,) # flatten is nothing but single dimensional array
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# 2) arange()

## arange() by default create an object of ndarray with 1-D array only. it can't build 2-D and N-D arrays
## To build 2D and ND arrays from arange(), we will use reshape() or shape() attribute.
## arange() is used for generating range of values with equal interval of value (Default interval (or) step value is 1)

### syntax: varname = numpy.arange(start)
### syntax: varname = numpy.arange(start,stop)
### syntax: varname = numpy.arange(start,stop,step)

In [36]:
import numpy as np

In [39]:
a = np.arange(10)
print(a,type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [41]:
a.shape=(2,5)
print(a,type(a))
print("---------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]] <class 'numpy.ndarray'>
---------------------
Dimensional= 2
Shape= (2, 5)
Size= 10
Internal datatype= int64


In [42]:
a = np.arange(10,22)
print(a,type(a))
print("-------------------")
a.shape=(4,3)
print(a,type(a))
print("---------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'>
-------------------
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] <class 'numpy.ndarray'>
---------------------
Dimensional= 2
Shape= (4, 3)
Size= 12
Internal datatype= int64


In [43]:
a = np.arange(10,106,5)
print(a,type(a))
print("-------------------")
a.shape=(5,4)
print(a,type(a))
print("---------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105] <class 'numpy.ndarray'>
-------------------
[[ 10  15  20  25]
 [ 30  35  40  45]
 [ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]] <class 'numpy.ndarray'>
---------------------
Dimensional= 2
Shape= (5, 4)
Size= 20
Internal datatype= int64


# linspace()
## linspace() stands for equal linear generated value.
## syntax: varname = numpy.linspace(start,stop,num,endpoint,returnstep,dtype)

In [44]:
import numpy as np

In [45]:
a = np.linspace(1,3)
print(a,type(a))

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ] <class 'numpy.ndarray'>


In [46]:
a = np.linspace(1,3,num=5) # equal intervals
print(a,type(a))

[1.  1.5 2.  2.5 3. ] <class 'numpy.ndarray'>


In [47]:
a = np.linspace(1,3,num=5,endpoint=False)
print(a,type(a))

[1.  1.4 1.8 2.2 2.6] <class 'numpy.ndarray'>


In [48]:
a = np.linspace(1,3,num=5,endpoint=True)
print(a,type(a))

[1.  1.5 2.  2.5 3. ] <class 'numpy.ndarray'>


In [49]:
a = np.linspace(1,3,num=5,endpoint=False,retstep=True)
print(a,type(a))

(array([1. , 1.4, 1.8, 2.2, 2.6]), np.float64(0.4)) <class 'tuple'>


In [50]:
a = np.linspace(1,3,num=5,endpoint=False,retstep=False)
print(a,type(a))

[1.  1.4 1.8 2.2 2.6] <class 'numpy.ndarray'>


In [51]:
a = np.linspace(1,3,num=5,endpoint=False,retstep=True,dtype=int)
print(a,type(a))

(array([1, 1, 1, 2, 2]), np.float64(0.4)) <class 'tuple'>


In [52]:
a = np.linspace(1,3,num=5,endpoint=False,retstep=True,dtype=bool)
print(a,type(a))

(array([ True,  True,  True,  True,  True]), np.float64(0.4)) <class 'tuple'>


In [53]:
a = np.linspace(1,3,num=5,endpoint=False,retstep=True,dtype=complex)
print(a,type(a))

(array([1. +0.j, 1.4+0.j, 1.8+0.j, 2.2+0.j, 2.6+0.j]), np.float64(0.4)) <class 'tuple'>


# 4)Zeros()
## In NumPy, zeros() is a function used to create an array filled entirely with zeros. It's super handy when you need a placeholder or want to initialize an array before populating it with actual data.
## syntax: varname = numpy.zeros(shape,dtype)

In [54]:
import numpy as np

In [55]:
a = np.zeros(8)
print(a,type(a))

[0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [56]:
a = np.zeros(8,dtype=int)
print(a,type(a))

[0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [57]:
A =a.reshape(2,4)
print(A)

[[0 0 0 0]
 [0 0 0 0]]


In [59]:
A =a.reshape(4,2)
print(A)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [60]:
A =a.reshape(1,8)
print(A)

[[0 0 0 0 0 0 0 0]]


In [61]:
A =a.reshape(8,1)
print(A)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [62]:
A =a.reshape(2,4)
print(A)
print("-----------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[0 0 0 0]
 [0 0 0 0]]
-----------------------
Dimensional= 2
Shape= (2, 4)
Size= 8
Internal datatype= int64


In [64]:
a = np.zeros((3,3,3),dtype=int)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [65]:
a = np.zeros((4,4),dtype=int)
print(a,type(a))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>


In [66]:
a = np.zeros((4,4,4),dtype=int)
print(a,type(a))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] <class 'numpy.ndarray'>


# 5) ones()
## In NumPy, ones() is a function that creates an array filled entirely with the number 1. It's perfect when you need a default array of ones for initialization, testing, or mathematical operations.
## syntax: varname = numpy.ones(shape,dtype)

In [67]:
import numpy as np

In [69]:
A = np.ones(6)
print(A,type(A))

[1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [72]:
A = np.ones((2,3),dtype=int)
print(A,type(A),id(A))
print("-------------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[1 1 1]
 [1 1 1]] <class 'numpy.ndarray'> 1797938574512
-------------------------
Dimensional= 2
Shape= (2, 3)
Size= 6
Internal datatype= int64


In [73]:
A = np.ones((3,4,4),dtype=int)
print(A,type(A),id(A))
print("-------------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] <class 'numpy.ndarray'> 1797938567408
-------------------------
Dimensional= 3
Shape= (3, 4, 4)
Size= 48
Internal datatype= int64


In [74]:
A = np.ones((3,4,4),dtype=bool)
print(A,type(A),id(A))
print("-------------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]] <class 'numpy.ndarray'> 1797938565680
-------------------------
Dimensional= 3
Shape= (3, 4, 4)
Size= 48
Internal datatype= bool


In [75]:
A = np.ones((4,4,4),dtype=float)
print(A,type(A),id(A))
print("-------------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] <class 'numpy.ndarray'> 1797938574992
-------------------------
Dimensional= 3
Shape= (4, 4, 4)
Size= 64
Internal datatype= float64


In [76]:
A = np.ones((4,4,4),dtype=complex)
print(A,type(A),id(A))
print("-------------------------")
print("Dimensional=",A.ndim)
print("Shape=",A.shape)
print("Size=",A.size)
print("Internal datatype=",A.dtype)

[[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]] <class 'numpy.ndarray'> 1797938565680
-------------------------
Dimensional= 3
Shape= (4, 4, 4)
Size= 64
Internal datatype= complex128


# 6) Identity()
## This function is always build identity (or) unit matrix.
## syntax: varname = numpy.identity(N,dtype) 
### Here N represents either we can take rows (or) cols and PVM takes as NxN matrix.

In [77]:
import numpy as np

In [78]:
a = np.identity(2)
print(a,type(a),id(a))

[[1. 0.]
 [0. 1.]] <class 'numpy.ndarray'> 1797938567024


In [79]:
a = np.identity(4,dtype=int)
print(a,type(a),id(a))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'> 1797938565296


In [80]:
a = np.identity(4,dtype=bool)
print(a,type(a),id(a))
print("----------------------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]] <class 'numpy.ndarray'> 1797938572016
----------------------------------------------
Dimensional= 2
Shape= (4, 4)
Size= 16
Internal datatype= bool


# 7)eye()
## This function is used to create a 2D array with ones on the diagonal and zeros elsewhere.
## It is commonly used in linear algebra and matrix operation.
## It is useful for generating matrices to transform, rotate (or) scale vector.
## Syntax: varname = numpy.eye(N,M=none,K=0,dtype)
### N = No of rows in output
### M = No of cols in output
### K = Index of the diagonal
### dtype = Datatype of the returned array

In [81]:
import numpy as np

In [82]:
a = np.eye(3)
print(a,type(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>


In [83]:
a = np.eye(N=4, M=5, k=1, dtype=int, order='F')
print(a,type(a))

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [89]:
a = np.eye(N=5, M=6, k=1, dtype=int, order='F')
print(a,type(a))

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]] <class 'numpy.ndarray'>


# 8) Full()
## In NumPy, full() is a function used to create an array of a specified shape, filled with a specified value. It's a flexible way to initialize arrays when you want every element to start with the same number — not just zeros or ones.
## syntax: varname = numpy.full(shape,fill_value,dtype)

In [90]:
import numpy as np

In [94]:
a = np.full((3,2),9,dtype=int)
print(a,type(a))

[[9 9]
 [9 9]
 [9 9]] <class 'numpy.ndarray'>


In [95]:
a = np.full((4,4),2,dtype=int)
print(a,type(a))

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]] <class 'numpy.ndarray'>


In [98]:
a = np.full((4,4),5,dtype=int)
print(a,type(a))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] <class 'numpy.ndarray'>


In [99]:
a = np.full((3,2),True)
print(a,type(a))

[[ True  True]
 [ True  True]
 [ True  True]] <class 'numpy.ndarray'>


In [100]:
a = np.full((4,4),"Vinay")
print(a,type(a))

[['Vinay' 'Vinay' 'Vinay' 'Vinay']
 ['Vinay' 'Vinay' 'Vinay' 'Vinay']
 ['Vinay' 'Vinay' 'Vinay' 'Vinay']
 ['Vinay' 'Vinay' 'Vinay' 'Vinay']] <class 'numpy.ndarray'>


In [101]:
a = np.full((4,4),"Vinnu")
print(a,type(a))
print("----------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[['Vinnu' 'Vinnu' 'Vinnu' 'Vinnu']
 ['Vinnu' 'Vinnu' 'Vinnu' 'Vinnu']
 ['Vinnu' 'Vinnu' 'Vinnu' 'Vinnu']
 ['Vinnu' 'Vinnu' 'Vinnu' 'Vinnu']] <class 'numpy.ndarray'>
----------------------------
Dimensional= 2
Shape= (4, 4)
Size= 16
Internal datatype= <U5


# 9) v & h stack
## In NumPy, vstack() and hstack() are used to stack arrays vertically or horizontally, respectively. They're super useful when you're combining arrays to build larger structures.

In [102]:
import numpy as np

In [103]:
a = np.array([1, 2])
b = np.array([3, 4])
result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]]


In [104]:
a = np.array([1, 2])
b = np.array([3, 4])
result = np.hstack((a, b))
print(result)

[1 2 3 4]


In [105]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stack: adds rows
v_result = np.vstack((a, b))
print("Vertical Stack:\n", v_result)

# Horizontal stack: adds columns
h_result = np.hstack((a, b))
print("Horizontal Stack:\n", h_result)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [106]:
a = np.array([[1, 2], [3, 4], [11,22]])
b = np.array([[5, 6], [7, 8],[23,43]])

# Vertical stack: adds rows
v_result = np.vstack((a, b))
print("Vertical Stack:\n", v_result)
print("--------------------------------")
print("Dimensional=",v_result.ndim)
print("Shape=",v_result.shape)
print("Size=",v_result.size)
print("Internal datatype=",v_result.dtype)
print("--------------------------------")
# Horizontal stack: adds columns
h_result = np.hstack((a, b))
print("Horizontal Stack:\n", h_result)
print("--------------------------------")
print("Dimensional=",h_result.ndim)
print("Shape=",h_result.shape)
print("Size=",h_result.size)
print("Internal datatype=",h_result.dtype)

Vertical Stack:
 [[ 1  2]
 [ 3  4]
 [11 22]
 [ 5  6]
 [ 7  8]
 [23 43]]
--------------------------------
Dimensional= 2
Shape= (6, 2)
Size= 12
Internal datatype= int64
--------------------------------
Horizontal Stack:
 [[ 1  2  5  6]
 [ 3  4  7  8]
 [11 22 23 43]]
--------------------------------
Dimensional= 2
Shape= (3, 4)
Size= 12
Internal datatype= int64


# Random numbers generating in numpy

# numpy.random
## 1) randint()
## 2) randn()
## 3) normal()
## 4) rand()
## 5) uniform()
## 6) shuffle()¶

## a) randint():-
### It will generate random integer value between the specified values range.
### syntax: randint(low, high=none,size=none,dtype=int)
## Note: It Will Generate only one int value

In [111]:
import numpy as np

In [112]:
a = np.random.randint(10)
print(a,type(a),id(a))

6 <class 'int'> 140725240181832


In [113]:
a = np.random.randint(10)
print(a,type(a),id(a))

0 <class 'int'> 140725240181640


In [114]:
a = np.random.randint(10)
print(a,type(a),id(a))

1 <class 'int'> 140725240181672


In [115]:
a = np.random.randint(10)
print(a,type(a),id(a))

3 <class 'int'> 140725240181736


In [117]:
print(np.random.randint(10,100))

31


In [118]:
print(np.random.randint(10,100))

23


In [119]:
print(np.random.randint(100,200))

192


In [120]:
print(np.random.randint(1000,9999))

4451


In [121]:
print(np.random.randint(1000,9999))

4675


In [122]:
print(np.random.randint(1000,9999))

1700


In [123]:
a = np.random.randint(10,20,size=5)
print(a,type(a),id(a))

[14 17 12 17 12] <class 'numpy.ndarray'> 1797948750704


In [124]:
a = np.random.randint(10,30,size=5)
print(a,type(a),id(a))

[28 16 28 20 10] <class 'numpy.ndarray'> 1797949162768


In [126]:
a = np.random.randint(10,30,size=(10,20))
print(a,type(a),id(a))

[[29 24 21 26 24 10 29 26 29 11 21 13 15 22 21 18 26 26 25 26]
 [24 14 10 21 23 27 24 16 20 16 12 28 12 12 25 26 12 21 25 17]
 [29 10 10 21 20 27 27 23 20 17 22 19 29 10 28 28 26 10 17 17]
 [25 26 20 18 19 11 11 22 20 13 12 25 19 28 17 13 20 27 13 24]
 [18 29 12 18 20 19 18 28 15 28 22 21 22 20 20 28 22 19 17 18]
 [19 23 28 25 23 17 29 22 28 24 17 11 13 26 18 21 24 23 27 10]
 [10 25 27 14 22 11 23 28 20 26 16 24 26 13 27 24 10 24 14 20]
 [21 25 18 17 13 13 12 13 13 28 12 16 15 20 29 12 19 27 10 15]
 [28 25 11 19 16 22 10 10 27 11 26 18 13 17 15 11 21 11 19 16]
 [16 25 15 26 29 24 15 19 17 19 18 15 15 16 22 28 25 21 18 14]] <class 'numpy.ndarray'> 1797949163632


In [127]:
a = np.random.randint(10,50,size=(5),dtype="int8")
print(a,type(a))
print("-----------------------------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[10 11 48 31 39] <class 'numpy.ndarray'>
-----------------------------------------------------
Dimensional= 1
Shape= (5,)
Size= 5
Internal datatype= int8


In [128]:
a = np.random.randint(10,50,size=(5,10),dtype="int8")
print(a,type(a))
print("-----------------------------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[[17 43 10 49 38 33 32 26 13 42]
 [33 47 36 16 30 18 41 15 43 21]
 [20 14 10 44 24 19 27 14 20 24]
 [15 21 48 47 39 42 42 33 24 37]
 [29 20 12 20 19 31 19 20 12 18]] <class 'numpy.ndarray'>
-----------------------------------------------------
Dimensional= 2
Shape= (5, 10)
Size= 50
Internal datatype= int8


In [129]:
a = np.random.randint(10,50,size=(5),dtype="int8")
print(a,type(a))
print("-----------------------------------------------------")
b = a.astype("float")
print("Dimensional=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal datatype=",b.dtype)

[29 15 12 10 47] <class 'numpy.ndarray'>
-----------------------------------------------------
Dimensional= 1
Shape= (5,)
Size= 5
Internal datatype= float64


# 2) rand()
## It will generate random integer value between 0.0 to 1.0 and it is also know as "uniform distribution".
### syntax: rand(d0,d1,.......,dn)

In [130]:
import numpy as np

In [131]:
a = np.random.rand()
print(a,type(a))

0.31488043545391253 <class 'float'>


In [132]:
a = np.random.rand(4) # 4 is the random uniform distribution
print(a,type(a))

[0.40762105 0.45401012 0.40110247 0.91949504] <class 'numpy.ndarray'>


In [133]:
a = np.random.rand(5) # 5 is the random uniform distribution
print(a,type(a))

[0.43850434 0.39174633 0.14800597 0.55127305 0.35644991] <class 'numpy.ndarray'>


In [135]:
a = np.random.rand(5,5)
print(a,type(a))
print("----------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[[0.12795673 0.74653108 0.78787381 0.43152681 0.20648928]
 [0.27043929 0.78984894 0.0893767  0.71339985 0.43714489]
 [0.58879721 0.36811305 0.98646215 0.59135913 0.18454187]
 [0.65013378 0.48343843 0.22510563 0.19310561 0.88567948]
 [0.13125036 0.92553813 0.58325193 0.48807399 0.36789159]] <class 'numpy.ndarray'>
----------------------------------
Dimensional= 2
Shape= (5, 5)
Size= 25
Internal datatype= float64


In [136]:
a = np.random.rand(3,5) 
print(a,type(a))
print("----------------------------------")
print("Dimensional=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal datatype=",a.dtype)

[[0.58793097 0.22488749 0.68766944 0.93485675 0.89855647]
 [0.55125953 0.80604469 0.60204724 0.2565868  0.87827219]
 [0.44585331 0.09533665 0.11420634 0.15686708 0.09061469]] <class 'numpy.ndarray'>
----------------------------------
Dimensional= 2
Shape= (3, 5)
Size= 15
Internal datatype= float64


# 3) randn()
## It will generate random integer values between 0.0 and 1.0,it is also know as "uniform distribution".
## syntax: rand(d0,d1,.......,dn)

In [138]:
import numpy as np

In [139]:
a = np.random.randn()
print(a,type(a))

-0.43260500596267143 <class 'float'>


In [140]:
a = np.random.randn()
print(a,type(a))

-1.4249476571858375 <class 'float'>


In [141]:
a = np.random.randn(2,2)
print(a,type(a))

[[-0.253183   -0.41437242]
 [ 1.04565726 -0.78711078]] <class 'numpy.ndarray'>


In [142]:
a = np.random.randn(3,3)
print(a,type(a))

[[ 0.72606499  0.77627434  1.25898873]
 [-0.26565962 -0.50958882 -0.66969701]
 [ 0.70974785 -0.94278795 -0.09391978]] <class 'numpy.ndarray'>


# 4) uniform()
## It will generate random integer value between users choice start and stop, uniform distribution.
## syntax: varname = np.uniform(10,80)

In [143]:
a = np.random.uniform(20,60)
print(a)

24.287203022146528


In [144]:
a = np.random.uniform(20,40)
print(a)

33.11811291279217


In [145]:
a = np.random.uniform(20,60,size=10)
print(a)

[28.22777192 56.64955723 24.66690691 20.64397913 32.63068335 38.38751778
 40.77445872 34.63633057 20.14698909 52.64990648]


In [146]:
a = np.random.uniform(20,60,size=(3,3))
print(a)

[[24.1046908  53.03135588 48.67324344]
 [24.2413403  57.53888896 31.49311009]
 [47.37293453 31.66356184 39.28392815]]


In [147]:
a = np.random.uniform(20,60,size=(5,5))
print(a)

[[32.96084079 52.9287492  52.17139105 52.53567651 24.38621201]
 [40.41906796 43.69222587 45.46625114 27.46540893 58.12385183]
 [55.31045345 54.62996717 52.241955   38.2570698  47.34152894]
 [37.86620969 45.08775784 27.45721775 52.97587331 36.13949983]
 [51.00847819 51.87154208 51.75140903 57.67810277 20.15917613]]


In [148]:
a = np.random.uniform(20,60,size=(2,3,3,3))
print(a)

[[[[52.53816091 34.62098141 20.03971244]
   [56.82220052 25.83997929 50.84822772]
   [33.91292632 42.68151798 37.01583136]]

  [[27.8095972  31.09674072 29.25608736]
   [27.35125689 28.42833168 29.14869127]
   [21.9963722  49.4703748  38.75863466]]

  [[52.62293326 49.69338615 26.46107212]
   [53.1285505  34.98525433 36.07920744]
   [43.73791459 47.40006157 45.75165487]]]


 [[[25.15775373 20.33033206 52.25619209]
   [35.32450814 43.66163978 23.87148165]
   [49.46145474 38.3026353  44.85558095]]

  [[36.00267765 26.0077831  21.41094326]
   [30.51975114 24.4316885  51.89395634]
   [34.12215585 42.99830398 50.09855601]]

  [[41.01792656 24.73776305 56.92412149]
   [33.02032785 32.38953272 55.11711543]
   [39.63893958 31.78329247 49.90651745]]]]


# 5) normal()
## syntax: varname = np.noraml(loc=0,scale=1.0,size=None) # Here loc is mean and scale is standard deviation

In [149]:
a = np.random.normal()
print(a,type(a))

0.8052763108291853 <class 'float'>


In [150]:
a = np.random.normal(10,3)
print(a,type(a))

14.325162150986698 <class 'float'>


In [151]:
a = np.random.normal(10,3,size=(5,5))
print(a,type(a))

[[12.73235113  7.85044903  9.8446124  10.44732278 12.54060505]
 [15.70293529 13.67440301  8.95388486  6.39027288  4.92496127]
 [12.59632896 11.90154847 10.35205605  7.13536342  8.66367703]
 [11.78527133 11.43041539  9.3412316   6.8127546   9.17876639]
 [15.1670883  14.03216001  7.51019825 11.25280718 12.49496254]] <class 'numpy.ndarray'>


# 6) shuffle()
## syntax: varname = numpy.random.shuffle(x)

In [153]:
a1 = np.array([10,20,30,40,50])
np.random.shuffle(a1)
print("-------------------------")
print("Shuffled value=",a1)

-------------------------
Shuffled value= [20 50 10 30 40]


In [154]:
a1 = np.array([10,20,30,40,50])
a=np.random.shuffle(a1)
print(a,type(a))
print("-------------------------")
print("Shuffled value=",a1)

None <class 'NoneType'>
-------------------------
Shuffled value= [10 20 40 30 50]
