In [1]:
import numpy as np

In [2]:
a = np.array([[10,20,30],[20,10,40],[10,50,60]])
print(a)

[[10 20 30]
 [20 10 40]
 [10 50 60]]


In [3]:
ind = np.where(a==10)
print(ind)

(array([0, 1, 2]), array([0, 1, 0]))


In [4]:
ind = np.where(a==20)
print(ind)

(array([0, 1]), array([1, 0]))


In [5]:
ind = np.where(a==30)
print(ind)

(array([0]), array([2]))


In [7]:
a = np.array(list("MISSISSIPPI"))
print(a)
print("---------------------------")
ind = np.where(a == "I")
print(ind)

['M' 'I' 'S' 'S' 'I' 'S' 'S' 'I' 'P' 'P' 'I']
---------------------------
(array([ 1,  4,  7, 10]),)


In [8]:
ind = np.where(a == "S")
print(ind)

(array([2, 3, 5, 6]),)


In [9]:
ind = np.where(a == "P")
print(ind)

(array([8, 9]),)


In [10]:
a = np.array(list("ABRAKADABRA"))
print(a)
print("---------------------------")
ind = np.where(a == "R")
print(ind)

['A' 'B' 'R' 'A' 'K' 'A' 'D' 'A' 'B' 'R' 'A']
---------------------------
(array([2, 9]),)


In [11]:
ind = np.where(a == "B")
print(ind)

(array([1, 8]),)


In [12]:
ind = np.where(a == "A")
print(ind)

(array([ 0,  3,  5,  7, 10]),)
