# Number of approaches to create an object of ndarray of numpy
## Here ndarray is pre-defined class present in numpy module.
## The purpose of ndarray object is that to store 1D, 2D and ND array data.
## In numpy module, we can create an object of ndarray with the following ways.
### a) arrays()
### b) arange()
### c) linspace()
### d) zeros()
### e) ones()
### f) full()
### g) identity
### h) eye()
### i) v&h stack
### j) numpy.random
### randint()
### randn()
### normal()
### uniform()
### rand()
### shuffle()

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip show numpy # Numpy summary 

Name: numpy
Version: 2.1.3
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2024, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED

In [5]:
pip list # number of available modules in numpy

Package                           Version
--------------------------------- -------------------
aiobotocore                       2.19.0
aiofiles                          24.1.0
aiohappyeyeballs                  2.4.4
aiohttp                           3.11.10
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.5.0
anaconda-anon-usage               0.7.1
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.7.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
astroid        

# a) array()
# This function is used for traditional python object into ndarray object.
## Syntax: Varname = numpy.array(object,dtype)

In [6]:
import numpy as np

In [7]:
a = 100
print(a,type(a),id(a))
print("----------------")
b = np.array(a)
print("-----------------")
print(b,type(b),id(b))

100 <class 'int'> 140718393049096
----------------
-----------------
100 <class 'numpy.ndarray'> 2230041941776


In [8]:
print(b.ndim)

0


In [9]:
print(b.shape)

()


In [10]:
print(b.size)

1


In [11]:
print(b.dtype)

int64


In [15]:
a = 4.6
print(a,type(a),id(a))
print("----------------")
b = np.array(a)
print(b,type(b),id(b))
print("-----------------")
print("Dimension=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal Datatype=",b.dtype)

4.6 <class 'float'> 2230042021520
----------------
4.6 <class 'numpy.ndarray'> 2230045315248
-----------------
Dimension= 0
Shape= ()
Size= 1
Internal Datatype= float64


In [16]:
a = 2+3j
print(a,type(a),id(a))
print("----------------")
b = np.array(a)
print(b,type(b),id(b))
print("-----------------")
print("Dimension=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal Datatype=",b.dtype)

(2+3j) <class 'complex'> 2230044652720
----------------
(2+3j) <class 'numpy.ndarray'> 2230045312944
-----------------
Dimension= 0
Shape= ()
Size= 1
Internal Datatype= complex128


In [17]:
a = "Vinay"
print(a,type(a),id(a))
print("----------------")
b = np.array(a)
print(b,type(b),id(b))
print("-----------------")
print("Dimension=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal Datatype=",b.dtype)

Vinay <class 'str'> 2230045212608
----------------
Vinay <class 'numpy.ndarray'> 2230045314768
-----------------
Dimension= 0
Shape= ()
Size= 1
Internal Datatype= <U5


In [18]:
r = range(7)
print(r,type(r),id(r))

range(0, 7) <class 'range'> 2230045395296


In [19]:
for val in r:
    print(val,end="\t")

0	1	2	3	4	5	6	

In [20]:
for val in range(0,21):
    print(val,end="\t")

0	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	

In [21]:
for val in range(0,21,2):
    print(val,end="\t")

0	2	4	6	8	10	12	14	16	18	20	

In [23]:
r = range(0,31,2)
a = np.array(r)
print(a,type(a))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30] <class 'numpy.ndarray'>


In [25]:
r = range(0,31,3)
a = np.array(r)
print(a,type(a))

[ 0  3  6  9 12 15 18 21 24 27 30] <class 'numpy.ndarray'>


In [26]:
r = range(10,51,5)
a = np.array(r)
print(a,type(a))

[10 15 20 25 30 35 40 45 50] <class 'numpy.ndarray'>


In [28]:
r = range(10,51,5)
b = np.array(r)
print(a,type(b))
print("-----------------")
print("Dimension=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal Datatype=",b.dtype)

[10 15 20 25 30 35 40 45 50] <class 'numpy.ndarray'>
-----------------
Dimension= 1
Shape= (9,)
Size= 9
Internal Datatype= int64


In [29]:
a = np.array(range(6),dtype=float)
print(a,type(a))

[0. 1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [38]:
a = np.array(range(0,16))
a.shape=(4,4)
print(a,type(a))
print("-----------------")
print("Dimension=",b.ndim)
print("Shape=",b.shape)
print("Size=",b.size)
print("Internal Datatype=",b.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
-----------------
Dimension= 1
Shape= (9,)
Size= 9
Internal Datatype= int64


In [44]:
a = np.array(range(0,16))
a.shape=(8,2)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (8, 2)
Size= 16
Internal Datatype= int64


In [45]:
a = np.array(range(0,16))
a.shape=(2,8)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 8)
Size= 16
Internal Datatype= int64


In [41]:
a.shape=(16,) # Flatten the list

In [42]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# b) arange()
# arange() is used for generating range of values with equal interval of values.
## Syntax-1: Varname = numpy.arange(Start) ---> It will generate range of value 0 to start -1
## Syntax-2: Varname = numpy.arange(Start,Stop) ---> It will generate range of value start to stop -1
## Syntax-3: Varname = numpy.arange(Start,Stop,Step) --> It will generate range of value start to stop -1 and maintaining equal interval steps.

# arange() by default creates an object of ndarray with 1D array only. it can't build 2D and ND arrays.
## To build 2D and ND arrays from arange() function, we use reshape() and shape attribute.

In [47]:
a = np.arange(10)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
-----------------
Dimension= 1
Shape= (10,)
Size= 10
Internal Datatype= int64


In [49]:
a.shape=(5,2)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (5, 2)
Size= 10
Internal Datatype= int64


In [51]:
a = np.arange(10,22)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'>
-----------------
Dimension= 1
Shape= (12,)
Size= 12
Internal Datatype= int64


In [53]:
a.shape=(2,2,3)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (2, 2, 3)
Size= 12
Internal Datatype= int64


In [54]:
a = np.arange(10,22).reshape(2,2,3)
print(a,type(a))

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>


In [55]:
a = np.arange(10,22).reshape(2,3,2)
print(a,type(a))

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]] <class 'numpy.ndarray'>


In [56]:
a = np.arange(10,22).reshape(4,3)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (4, 3)
Size= 12
Internal Datatype= int64


In [58]:
a = np.arange(10,106,5)
print(a,type(a))

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105] <class 'numpy.ndarray'>


In [59]:
a = np.arange(10,106,5).reshape(4,5)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[ 10  15  20  25  30]
 [ 35  40  45  50  55]
 [ 60  65  70  75  80]
 [ 85  90  95 100 105]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (4, 5)
Size= 20
Internal Datatype= int64


In [60]:
a = np.arange(10,106,5).reshape(2,5,2)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[ 10  15]
  [ 20  25]
  [ 30  35]
  [ 40  45]
  [ 50  55]]

 [[ 60  65]
  [ 70  75]
  [ 80  85]
  [ 90  95]
  [100 105]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (2, 5, 2)
Size= 20
Internal Datatype= int64


# c) linspace()
## It create an list of numbers that are evenly spaced between two values.
## Syntax: varname = numpy.linspace(start,stop,num,endpoint,retstep,dtype)

In [61]:
a = np.linspace(1,10) # defaultly it give 50 equally generated values.
print(a,type(a))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ] <class 'numpy.ndarray'>


In [62]:
a = np.linspace(1,10,num=5) # defaultly it give 5 equally generated values.
print(a,type(a))

[ 1.    3.25  5.5   7.75 10.  ] <class 'numpy.ndarray'>


In [64]:
a = np.linspace(1,10,num=15) # defaultly it give 15 equally generated values.
print(a,type(a))

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ] <class 'numpy.ndarray'>


In [65]:
a = np.linspace(1,100,num=15) # defaultly it give 15 equally generated values.
print(a,type(a))

[  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ] <class 'numpy.ndarray'>


In [66]:
a = np.linspace(1,100,num=5,endpoint=False) # Endpoint = False means it won't give last value.
print(a,type(a))

[ 1.  20.8 40.6 60.4 80.2] <class 'numpy.ndarray'>


In [68]:
a = np.linspace(1,100,num=15,endpoint=False,retstep=True) 
print(a,type(a))

(array([ 1. ,  7.6, 14.2, 20.8, 27.4, 34. , 40.6, 47.2, 53.8, 60.4, 67. ,
       73.6, 80.2, 86.8, 93.4]), np.float64(6.6)) <class 'tuple'>


In [69]:
a = np.linspace(1,100,num=10,endpoint=False,retstep=True) 
print(a,type(a))

(array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1]), np.float64(9.9)) <class 'tuple'>


In [70]:
a = np.linspace(1,100,num=10,endpoint=False,retstep=True,dtype=int) 
print(a,type(a))

(array([ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]), np.float64(9.9)) <class 'tuple'>


In [72]:
a = np.linspace(1,100,num=15,endpoint=False,retstep=True,dtype=int) 
print(a,type(a))

(array([ 1,  7, 14, 20, 27, 34, 40, 47, 53, 60, 67, 73, 80, 86, 93]), np.float64(6.6)) <class 'tuple'>


In [73]:
a = np.linspace(1,100,num=15,retstep=True,dtype=int) 
print(a,type(a))

(array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92, 100]), np.float64(7.071428571428571)) <class 'tuple'>


# d) Zeros()
## It creates an array filled with zeros. You choose the shape (like how many rows and columns), and NumPy fills it with 0.0.
## Syntax: varname = numpy.zeros(shape,dtype)

In [74]:
a = np.zeros(6)
print(a,type(a))

[0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [75]:
a = np.zeros(6,dtype=bool)
print(a,type(a))

[False False False False False False] <class 'numpy.ndarray'>


In [76]:
a = np.zeros(6,dtype=int)
print(a,type(a))

[0 0 0 0 0 0] <class 'numpy.ndarray'>


In [77]:
a = np.zeros((2,2),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[0 0]
 [0 0]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 2)
Size= 4
Internal Datatype= int64


In [78]:
a = np.zeros((2,2),dtype=float)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 2)
Size= 4
Internal Datatype= float64


In [79]:
a = np.zeros((2,2),dtype=bool)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[False False]
 [False False]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 2)
Size= 4
Internal Datatype= bool


In [80]:
a = np.zeros((3,3,3),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 3, 3)
Size= 27
Internal Datatype= int64


In [81]:
a = np.zeros((3,4,3),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 4, 3)
Size= 36
Internal Datatype= int64


In [82]:
a = np.zeros((3,4,3),dtype=bool)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 4, 3)
Size= 36
Internal Datatype= bool


# e) ones()
## It creates an array filled with ones. You choose the shape (like how many rows and columns), and NumPy fills it with 0.0.
## Syntax: varname = numpy.ones(shape,dtype)

In [83]:
a = np.ones(8)
print(a,type(a))

[1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [84]:
a = np.ones(8,dtype=bool)
print(a,type(a))

[ True  True  True  True  True  True  True  True] <class 'numpy.ndarray'>


In [85]:
a = np.ones(8,dtype=int)
print(a,type(a))

[1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>


In [86]:
a = np.ones((2,4),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[1 1 1 1]
 [1 1 1 1]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 4)
Size= 8
Internal Datatype= int64


In [87]:
a = np.ones((4,2),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[1 1]
 [1 1]
 [1 1]
 [1 1]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (4, 2)
Size= 8
Internal Datatype= int64


In [88]:
a = np.ones((2,4,3),dtype=int)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (2, 4, 3)
Size= 24
Internal Datatype= int64


In [89]:
a = np.ones((2,4,3),dtype=bool)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (2, 4, 3)
Size= 24
Internal Datatype= bool


# f) full()
## It creates an array of any shape you want, and fills it with a value you choose.
## syntax: varname = numpy.full(shape,fill_value,dtype)

In [90]:
a = np.full(8,9,dtype=int)
print(a,type(a))

[9 9 9 9 9 9 9 9] <class 'numpy.ndarray'>


In [91]:
a = np.full(8,5,dtype=int).reshape(2,4)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[5 5 5 5]
 [5 5 5 5]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (2, 4)
Size= 8
Internal Datatype= int64


In [92]:
a = np.full(8,3,dtype=int).reshape(4,2)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[3 3]
 [3 3]
 [3 3]
 [3 3]] <class 'numpy.ndarray'>
-----------------
Dimension= 2
Shape= (4, 2)
Size= 8
Internal Datatype= int64


In [97]:
a = np.full((3,3,3),7)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 3, 3)
Size= 27
Internal Datatype= int64


In [98]:
a = np.full((3,3,4),7)
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 3, 4)
Size= 36
Internal Datatype= int64


In [99]:
a = np.full((3,3,4),"Vinay")
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']]

 [['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']]

 [['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']
  ['Vinay' 'Vinay' 'Vinay' 'Vinay']]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 3, 4)
Size= 36
Internal Datatype= <U5


In [101]:
a = np.full((3,4,4),"Sai")
print(a,type(a))
print("-----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal Datatype=",a.dtype)

[[['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']]

 [['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']]

 [['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']
  ['Sai' 'Sai' 'Sai' 'Sai']]] <class 'numpy.ndarray'>
-----------------
Dimension= 3
Shape= (3, 4, 4)
Size= 48
Internal Datatype= <U3


# g) identity()
## np.identity() creates a square matrix (same number of rows and columns) with:
## 1s on the diagonal
## 0s everywhere else
## This is called an identity matrix, and it's super useful in linear algebra.
### syntax: varname = numpy.identity(N,dtype)

In [102]:
a = np.identity(2)
print(a,type(a))

[[1. 0.]
 [0. 1.]] <class 'numpy.ndarray'>


In [103]:
a = np.identity(2,dtype=int)
print(a,type(a))

[[1 0]
 [0 1]] <class 'numpy.ndarray'>


In [104]:
a = np.identity(3,dtype=int)
print(a,type(a))

[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'>


In [105]:
a = np.identity(4,dtype=int)
print(a,type(a))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'>


In [106]:
a = np.identity(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [107]:
a = np.identity(6,dtype=int)
print(a,type(a))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]] <class 'numpy.ndarray'>


In [108]:
a = np.identity((2,4),dtype=int) # its not possible in this case
print(a,type(a))

TypeError: 'tuple' object cannot be interpreted as an integer

# h) eye()
## np.eye() creates a 2D array (matrix) with:
## 1s on the diagonal
## 0s everywhere else Just like identity(), but with more control over rows and columns.
## syntax: varname = numpy.eye(N,M=None,K=0,dtype)

In [109]:
a = np.eye(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [110]:
a = np.eye(5,k=-1,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]] <class 'numpy.ndarray'>


In [111]:
a = np.eye(5,k=-2,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [112]:
a = np.eye(5,k=-3,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]] <class 'numpy.ndarray'>


In [113]:
a = np.eye(5,k=-4,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]] <class 'numpy.ndarray'>


In [114]:
a = np.eye(5,k=2,dtype=int)
print(a,type(a))

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [115]:
a = np.eye(5,k=3,dtype=int)
print(a,type(a))

[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [116]:
a = np.eye(5,k=4,dtype=int)
print(a,type(a))

[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [117]:
a = np.eye(5,k=5,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>


In [118]:
a = np.eye(5,3,dtype=int)
print(a,type(a))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


In [119]:
a = np.eye(3,5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [121]:
a = np.eye(5,3,k=1,dtype=int)
print(a,type(a))

[[0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


In [122]:
a = np.eye(10,15,dtype=int)
print(a,type(a))

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]] <class 'numpy.ndarray'>


In [123]:
a = np.eye(10,10,dtype=int)
print(a,type(a))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]] <class 'numpy.ndarray'>


# Random number Neneration in Numpy
## j) numpy.random
### 1) randint()
### 2) rand()
### 3) randn()
### 4) uniform()
### 5) shuffle()
### 6) normal()

# 1) randint()
## It will generate random interger values between the specified range.
### syntax: randint(low, high=None, size=None, dtype=int)

In [124]:
a = np.random.randint(10)
print(a,type(a))

6 <class 'int'>


In [125]:
a = np.random.randint(10)
print(a,type(a))

3 <class 'int'>


In [126]:
a = np.random.randint(10)
print(a,type(a))

2 <class 'int'>


In [127]:
a = np.random.randint(1000,10000) # random value comes bw 1000 100000 any 4 digit numberw will give output
print(a,type(a))

1432 <class 'int'>


In [128]:
a = np.random.randint(1000,10000)
print(a,type(a))

4938 <class 'int'>


In [129]:
a = np.random.randint(1000,10000)
print(a,type(a))

5763 <class 'int'>


In [130]:
a = np.random.randint(100,1000)
print(a,type(a))

936 <class 'int'>


In [131]:
a = np.random.randint(100,1000)
print(a,type(a))

822 <class 'int'>


In [132]:
a = np.random.randint(10,20,size=5)
print(a,type(a))

[14 19 13 13 19] <class 'numpy.ndarray'>


In [133]:
a = np.random.randint(10,20,size=5)
print(a,type(a))

[19 11 13 18 15] <class 'numpy.ndarray'>


In [134]:
a = np.random.randint(10,20,size=6)
print(a,type(a))

[16 15 15 10 19 17] <class 'numpy.ndarray'>


In [135]:
a = np.random.randint(10,20,size=6)
print(a,type(a))

[13 19 11 16 17 10] <class 'numpy.ndarray'>


In [136]:
a = np.random.randint(10,20,size=16) # size is out of range it will duplicates
print(a,type(a))

[13 14 12 11 15 10 13 13 13 16 17 11 10 12 13 17] <class 'numpy.ndarray'>


In [137]:
a = np.random.randint(10,20,size=(3,3))
print(a,type(a))

[[10 18 16]
 [15 16 18]
 [13 14 17]] <class 'numpy.ndarray'>


In [138]:
a = np.random.randint(10,20,size=(3,3))
print(a,type(a))

[[15 10 14]
 [18 15 14]
 [15 13 19]] <class 'numpy.ndarray'>


In [139]:
a = np.random.randint(10,20,size=(4,3))
print(a,type(a))

[[11 19 15]
 [17 11 17]
 [14 16 12]
 [19 14 12]] <class 'numpy.ndarray'>


In [140]:
a = np.random.randint(10,20,size=(3,2))
print(a,type(a))

[[12 19]
 [14 12]
 [16 10]] <class 'numpy.ndarray'>


In [142]:
a = np.random.randint(10,20,size=(3,3,3))
print(a,type(a))

[[[16 12 18]
  [13 10 14]
  [19 12 14]]

 [[13 13 19]
  [14 16 16]
  [14 10 19]]

 [[11 16 10]
  [16 12 17]
  [15 16 14]]] <class 'numpy.ndarray'>


In [143]:
a = np.random.randint(10,50,size=20)
print(a,type(a))

[38 13 12 39 42 26 23 42 16 25 20 44 10 46 19 42 28 23 31 22] <class 'numpy.ndarray'>


In [144]:
import sys
a = np.random.randint(10,50,size=20)
print(a,type(a))
print("Default DT=",a.dtype)
print("Total Memory space of ndarray a =",sys.getsizeof(a))

[40 29 18 43 44 10 26 49 30 35 29 18 30 15 17 24 44 32 39 42] <class 'numpy.ndarray'>
Default DT= int32
Total Memory space of ndarray a = 192


In [145]:
import sys
a = np.random.randint(10,50,size=20,dtype="int8")
print(a,type(a))
print("Default DT=",a.dtype)
print("Total Memory space of ndarray a =",sys.getsizeof(a))

[28 10 18 48 19 25 15 45 14 16 20 37 30 14 12 45 13 40 38 19] <class 'numpy.ndarray'>
Default DT= int8
Total Memory space of ndarray a = 132


In [146]:
import sys
a = np.random.randint(10,50,size=20,dtype="int16")
print(a,type(a))
print("Default DT=",a.dtype)
print("Total Memory space of ndarray a =",sys.getsizeof(a))

[16 37 29 28 37 19 24 18 40 22 22 19 25 12 42 36 45 12 31 15] <class 'numpy.ndarray'>
Default DT= int16
Total Memory space of ndarray a = 152


In [147]:
a = np.random.randint(10,50,size=20,dtype="int8")
print(a,type(a))
b = a.astype("float")# astype is used for converting one ndarray object type another object.
print(b,type(a))

[31 28 25 31 12 21 49 36 25 44 23 31 44 33 46 19 28 11 42 36] <class 'numpy.ndarray'>
[31. 28. 25. 31. 12. 21. 49. 36. 25. 44. 23. 31. 44. 33. 46. 19. 28. 11.
 42. 36.] <class 'numpy.ndarray'>


In [149]:
a = np.random.randint(10,50,size=(5,5),dtype="int8")
print(a,type(a))
b = a.astype("float") # astype is used for converting one ndarray object type to another object.
print(b,type(a))

[[30 12 30 29 17]
 [46 27 18 34 15]
 [20 45 34 15 48]
 [34 46 22 21 35]
 [16 45 44 39 37]] <class 'numpy.ndarray'>
[[30. 12. 30. 29. 17.]
 [46. 27. 18. 34. 15.]
 [20. 45. 34. 15. 48.]
 [34. 46. 22. 21. 35.]
 [16. 45. 44. 39. 37.]] <class 'numpy.ndarray'>


# 2) randn()
## It will Generate random inter values between 0.0 and 1.0(uniform distribution)
## syntax: rand(d0,d1,.....,dn)

In [150]:
a = np.random.rand()
print(a)

0.8186823021723434


In [151]:
a = np.random.rand()
print(a)

0.9362096719026861


In [152]:
a = np.random.rand()
print(a)

0.18460237313887906


In [153]:
a = np.random.rand(5)
print(a)

[0.18201518 0.28035347 0.17363936 0.47548884 0.31340813]


In [154]:
a = np.random.rand(3)
print(a)

[0.63423128 0.86991579 0.28362642]


In [155]:
a = np.random.rand(5,5)
print(a,type(a))

[[0.45284923 0.72147211 0.67008265 0.56110487 0.49599911]
 [0.00164849 0.75591585 0.63692939 0.80826694 0.53264474]
 [0.77101378 0.99246472 0.90505271 0.12778106 0.33790058]
 [0.52692966 0.38365659 0.81285583 0.71056439 0.77068837]
 [0.11563279 0.30036002 0.1739822  0.78263315 0.90972943]] <class 'numpy.ndarray'>


In [156]:
a = np.random.rand(3,3)
print(a,type(a))

[[0.63143675 0.21518709 0.66375039]
 [0.43598521 0.71471723 0.46403627]
 [0.91424718 0.07285531 0.76693271]] <class 'numpy.ndarray'>


In [157]:
a = np.random.rand(2,3,3)
print(a,type(a))

[[[0.71362076 0.51916813 0.63586265]
  [0.09378495 0.26042821 0.40955222]
  [0.03308244 0.50740558 0.34010291]]

 [[0.40673751 0.63734556 0.97899997]
  [0.365505   0.09655859 0.04280173]
  [0.92353571 0.53476397 0.44057679]]] <class 'numpy.ndarray'>


# 3) uniform()
## Generating random integer values between programmer specified values.(start, stop) -- uniform distribution
## syntax:uniform(low=0.0,high=1.0,size=None)

In [158]:
a = np.random.uniform()
print(a,type(a))

0.6934263975067045 <class 'float'>


In [159]:
a = np.random.uniform()
print(a,type(a))

0.6026830847644169 <class 'float'>


In [160]:
a = np.random.uniform(10,30)
print(a,type(a))

19.61371854957152 <class 'float'>


In [161]:
a = np.random.uniform(10,30)
print(a,type(a))

14.68837902800207 <class 'float'>


In [163]:
a = np.random.uniform(1,3,size=10)
print(a,type(a))

[2.02645951 1.55807144 1.58531703 2.23101287 2.6889791  2.26041343
 1.95342725 1.76302851 2.60356949 1.12918919] <class 'numpy.ndarray'>


In [164]:
a = np.random.uniform(1,2,size=10)
print(a,type(a))

[1.84107421 1.66312757 1.51647309 1.46448891 1.8226818  1.55981793
 1.12873227 1.02104106 1.75486996 1.5937105 ] <class 'numpy.ndarray'>


In [165]:
a = np.random.uniform(1,5,size=(3,3,3))
print(a,type(a))

[[[3.79504998 2.44834898 2.7459411 ]
  [2.90681987 2.37033072 2.09437103]
  [2.78699704 3.48092727 1.08349197]]

 [[2.84129382 4.89483013 3.61120221]
  [2.98131277 4.23401867 2.24216772]
  [1.48385726 2.50471544 4.59910249]]

 [[2.00797779 1.91610174 1.45396896]
  [4.8064436  2.58224723 1.14133993]
  [4.84810839 3.84529181 2.94370446]]] <class 'numpy.ndarray'>


In [166]:
a = np.random.uniform(1,5,size=(3,3))
print(a,type(a))

[[3.46556815 1.53488067 3.52919868]
 [2.3908192  1.83287152 3.96547427]
 [2.68498762 2.47609876 2.60977323]] <class 'numpy.ndarray'>


In [167]:
a = np.random.uniform(1,5,size=(2,3,3,3))
print(a,type(a))

[[[[3.11949252 3.13861424 3.88507043]
   [4.01800115 4.55448395 3.46889317]
   [2.41942606 1.21327236 4.85316281]]

  [[4.75968372 1.06987689 2.32198557]
   [2.7758316  3.34143264 4.65470783]
   [1.59582442 4.35569444 3.47614288]]

  [[4.9737367  1.07477645 2.18683483]
   [2.50889687 1.64277866 1.03052227]
   [2.35262803 1.9096516  2.87976247]]]


 [[[2.96713583 3.31586165 2.65989858]
   [3.53741704 4.53498246 4.86099954]
   [1.97516203 2.46439826 4.45391254]]

  [[3.41589642 2.92378606 4.39906634]
   [2.45141874 1.93662004 4.04976789]
   [1.17957489 1.66587716 4.3557249 ]]

  [[4.84488961 3.5845913  1.72410308]
   [2.18076911 1.08959352 3.2641476 ]
   [3.57703326 4.38401417 4.50182843]]]] <class 'numpy.ndarray'>


# 4) randn()
## It will Generate random integer values between 0.0 and 1.0 (Normal distribution)
## Syntax: randn(d0,d1,d2,....,dn)

In [168]:
a = np.random.randn() # gives single value -ve or +ve
print(a,type(a))

-0.8791942978897859 <class 'float'>


In [169]:
a = np.random.randn()
print(a,type(a))

0.16021208296700626 <class 'float'>


In [170]:
a = np.random.randn()
print(a,type(a))

-1.1844249346322295 <class 'float'>


In [171]:
a = np.random.randn(2,3) # It gives 6 values 2 rows 3 col
print(a,type(a))

[[ 0.64359863 -1.09094322  0.44361189]
 [ 1.07814266  0.88162202 -0.96289142]] <class 'numpy.ndarray'>


In [172]:
a = np.random.randn(3,3)
print(a,type(a))

[[ 0.18273328  1.17127601 -1.47710493]
 [ 0.52518708  0.8550757  -0.19172042]
 [-0.34329759 -0.88217724  0.36406772]] <class 'numpy.ndarray'>


In [173]:
a = np.random.randn(3,3,3)
print(a,type(a))

[[[-0.92920976  1.57826017  0.92126962]
  [ 0.52146903 -1.06223861  0.7703057 ]
  [ 1.15997642 -0.9273093   0.27687895]]

 [[-1.04436791  0.35106703 -0.64587375]
  [-1.42332213  0.3870138  -2.18664109]
  [-1.2696737  -0.38573302 -0.29332348]]

 [[-1.32832383  0.18428167  1.30281692]
  [ 0.57179573  0.38315948 -1.2473908 ]
  [ 0.69207311 -0.07683879  1.46121898]]] <class 'numpy.ndarray'>


# 5) normal()
## It creates an array of random numbers that follow a normal (Gaussian) distribution — the classic bell curve!
## syntax: normal(loc=0.0, scale=1.0, size=None)

In [174]:
a = np.random.normal()
print(a,type(a))

0.5543902662411163 <class 'float'>


In [175]:
a = np.random.normal()
print(a,type(a))

-1.2107760639287215 <class 'float'>


In [176]:
a = np.random.normal(10,2,size=6)
print(a,type(a))

[10.01328991 11.71976521 10.89734097 13.26122001  5.85972925 12.28088166] <class 'numpy.ndarray'>


In [178]:
a = np.random.normal(10,2,size=(3,3))
print(a,type(a))

[[ 9.89017155  8.8325059   8.78723298]
 [11.68341279  9.44674615 14.21044682]
 [ 9.58408525  7.40782024  5.52003906]] <class 'numpy.ndarray'>


In [179]:
a = np.random.normal(10,2,size=(3,3))
print(a,type(a))

[[ 6.61183263 12.86052845  9.30309031]
 [ 9.99520071 10.17002788  9.56875203]
 [ 8.43871487 12.3826687  10.2312756 ]] <class 'numpy.ndarray'>


In [180]:
a = np.random.normal(10,2,size=(2,3,3))
print(a,type(a))

[[[ 9.13995039 11.28495562  7.33754944]
  [ 9.81582975 10.02394447 10.69888152]
  [ 9.9841975  12.82654857 12.37258296]]

 [[11.64572579 11.95215421 11.10100717]
  [ 9.08824462 11.55606484 10.9400802 ]
  [ 9.38413194 10.27552192 10.3911066 ]]] <class 'numpy.ndarray'>


In [181]:
a = np.random.normal(10,2,size=(3,3,3))
print(a,type(a))

[[[ 7.94710204 11.807253   12.36314482]
  [ 9.94895347 12.51896685  6.5037563 ]
  [10.01269509 11.22156996  6.84805925]]

 [[ 7.30864582 10.68579827 11.52998202]
  [10.49807905 10.47239761 11.90610849]
  [13.17955972  8.49195064 12.11069376]]

 [[ 7.12001748  8.56849802 11.17604101]
  [11.96094658 12.23915734  9.30873207]
  [10.99803008 10.28850413 10.17362186]]] <class 'numpy.ndarray'>


# 6) shuffle()
## It is nothing but re-organizing elements in the place of same element(mutable object)
## syntax: shuffle(x)

In [183]:
a = np.array([10,20,30,40,50])
print(a,type(a))
print("--------------------------")
np.random.shuffle(a)
print("Shuffled value=",a)

[10 20 30 40 50] <class 'numpy.ndarray'>
--------------------------
Shuffled value= [10 40 30 20 50]


In [184]:
np.random.shuffle(a)
print("Shuffled value=",a)

Shuffled value= [10 30 20 40 50]


In [185]:
np.random.shuffle(a)
print("Shuffled value=",a)

Shuffled value= [10 20 30 40 50]


In [186]:
a[2]

np.int64(30)

In [187]:
a[1]

np.int64(20)

In [188]:
a = np.random.randint(1,101,size=30)
print(a)

[94 51 74 57 79 98 50 81  6 57 52 14 79 56 34  4 73 30 97 21  5 79 88 68
 20 54 71 36 15 61]


In [189]:
np.random.shuffle(a)
print(a)

[73 81 15 98 79 79 61 57 51 57  5 34  6 97  4 21 94 56 79 71 30 54 74 88
 36 50 20 68 14 52]


In [190]:
a = np.random.randint(1,101,size=(5,6))
print(a,type(a))
print("-----------------------------")
np.random.shuffle(a)
print(a)

[[30 27 21 54 14 85]
 [19 94 82 68 55 33]
 [51 33 59 26 46 38]
 [12 98 92 87 87 16]
 [92 91 94  9 64 79]] <class 'numpy.ndarray'>
-----------------------------
[[30 27 21 54 14 85]
 [51 33 59 26 46 38]
 [12 98 92 87 87 16]
 [19 94 82 68 55 33]
 [92 91 94  9 64 79]]


In [191]:
a = np.random.randint(1,101,size=(5,6))
print(a,type(a))
print("-----------------------------")
np.random.shuffle(a)
print(a)

[[ 9 37 77 30  8 34]
 [60 77 55 60 16 66]
 [54 39 81 49  8 76]
 [57 62 57  6 71 71]
 [48 36 44 10 84 70]] <class 'numpy.ndarray'>
-----------------------------
[[48 36 44 10 84 70]
 [54 39 81 49  8 76]
 [ 9 37 77 30  8 34]
 [60 77 55 60 16 66]
 [57 62 57  6 71 71]]


# v & h & d stack()

In [193]:
a = np.array([10,20,30,40])
b = np.array([100,200,300,400])
c = np.hstack((a,b))
print(c,type(c))

[ 10  20  30  40 100 200 300 400] <class 'numpy.ndarray'>


In [194]:
a = np.array([100,200,300,400])
b = np.array([500,600,700,800])
c = np.hstack((a,b))
print(c,type(c))

[100 200 300 400 500 600 700 800] <class 'numpy.ndarray'>


In [196]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,15,25,35]])
b = np.array([[100,200,300],[500,600,700],[900,750,850]])
print("Matrix-A")
print(a,type(a))
print("--------------------------")
print("Matrix-B")
print(b,type(b))
print("--------------------------")
c = np.hstack((a,b))
print(c,type(c))

Matrix-A
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]] <class 'numpy.ndarray'>
--------------------------
Matrix-B
[[100 200 300]
 [500 600 700]
 [900 750 850]] <class 'numpy.ndarray'>
--------------------------
[[ 10  20  30  40 100 200 300]
 [ 50  60  70  80 500 600 700]
 [ 90  15  25  35 900 750 850]] <class 'numpy.ndarray'>


In [199]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,15,25,35]])
b = np.array([[100,200,300,790],[500,600,700,456]])
print("Matrix-A")
print(a,type(a))
print("--------------------------")
print("Matrix-B")
print(b,type(b))
print("--------------------------")
c = np.vstack((a,b))
print(c,type(c))

Matrix-A
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]] <class 'numpy.ndarray'>
--------------------------
Matrix-B
[[100 200 300 790]
 [500 600 700 456]] <class 'numpy.ndarray'>
--------------------------
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90  15  25  35]
 [100 200 300 790]
 [500 600 700 456]] <class 'numpy.ndarray'>
