## Here ndarray is pre-defined class present in numpy module
## The purpose of ndarray object is that to store 1D array or 2D array and ND array Data.
## In otherwords, To store 1D array or 2D array and ND array data in NumPy prog, we must create an obj of ndarray class. 
## In Numpy module, we can create an object of ndarray with the following ways.
- array()
- arange()
- linspace()
- zeros()
- ones()
- full()
- identity()
- eye()
- hstack()
- vstack()
- numpy.random
- randint()
- rand()
- uniform()
- randm()
- normal()
- shuffle()

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [96]:
pip show numpy 

Name: numpy
Version: 2.3.5
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2025, NumPy Developers.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are
 met:

     * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     * Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials provided
        with the distribution.

     * Neither the name of the NumPy Developers nor the names of any
        contributors may be used to endorse or promote products derived
        from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED

pip list

# 1) array()
## syntax: varname = numpy.array(object,type)
## This function is used for converting traditional python into ndarray object.

In [4]:
import numpy as np

In [5]:
b = 100
a = np.array(b)
print(a,type(a))

100 <class 'numpy.ndarray'>


In [6]:
print(a.ndim)

0


In [7]:
print(a.shape)

()


In [8]:
print(a.size)

1


In [9]:
print(a.dtype)

int64


In [10]:
b = 2.4
a = np.array(b)
print(a,type(a))
print("---------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

2.4 <class 'numpy.ndarray'>
---------------
Dimension= 0
Shape= ()
Size= 1
Internal DT= float64


In [11]:
b = "Vinay"
a = np.array(b)
print(a,type(a))
print("---------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

Vinay <class 'numpy.ndarray'>
---------------
Dimension= 0
Shape= ()
Size= 1
Internal DT= <U5


In [12]:
r = range(0,7)
r

range(0, 7)

In [13]:
for val in r:
    print(val, end="\t")

0	1	2	3	4	5	6	

In [14]:
for val in range(10,21):
    print(val, end="\t")

10	11	12	13	14	15	16	17	18	19	20	

In [15]:
for val in range(10,21,2):
    print(val,end="\t")

10	12	14	16	18	20	

In [16]:
r = range(10,51,2)
a = np.array(r)
print(a,type(a))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>


In [17]:
r = range(10,51,5)
a = np.array(r)
print(a,type(a))

[10 15 20 25 30 35 40 45 50] <class 'numpy.ndarray'>


In [18]:
r = range(10,51,10)
a = np.array(r)
print(a,type(a))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [19]:
r = range(10,51,5)
a = np.array(r)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[10 15 20 25 30 35 40 45 50] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (9,)
Size= 9
Internal DT= int64


In [20]:
r = range(10,51,5)
a = np.array(r,dtype=float)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[10. 15. 20. 25. 30. 35. 40. 45. 50.] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (9,)
Size= 9
Internal DT= float64


In [21]:
r = range(10,51,5)
a = np.array(r,dtype=complex)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[10.+0.j 15.+0.j 20.+0.j 25.+0.j 30.+0.j 35.+0.j 40.+0.j 45.+0.j 50.+0.j] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (9,)
Size= 9
Internal DT= complex128


In [22]:
a = np.array(range(6),dtype=float)
print(a,type(a))

[0. 1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [23]:
a = np.array(range(6),dtype=bool)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[False  True  True  True  True  True] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (6,)
Size= 6
Internal DT= bool


In [24]:
a = np.array(range(100,151,5))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

----------------
Dimension= 1
Shape= (11,)
Size= 11
Internal DT= int64


In [25]:
a = np.array(range(100,156,5))
print("Content of a=", a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

Content of a= [100 105 110 115 120 125 130 135 140 145 150 155]
----------------
Dimension= 1
Shape= (12,)
Size= 12
Internal DT= int64


In [26]:
# Now i want to reshare the 1D array into 2D array
# To reshape the ndarray object, we use 1) shape attribute 2) reshape() of ndarray object
# syntax: ndarray.shape=(rows,cols)
# syntax:ndarray.reshape(rows,cols)

In [27]:
a = np.array(range(100,156,5))
print("Content of a=", a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

Content of a= [100 105 110 115 120 125 130 135 140 145 150 155]
----------------
Dimension= 1
Shape= (12,)
Size= 12
Internal DT= int64


In [28]:
a.shape=(6,2)
a

array([[100, 105],
       [110, 115],
       [120, 125],
       [130, 135],
       [140, 145],
       [150, 155]])

In [29]:
a.shape=(4,3)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (4, 3)
Size= 12
Internal DT= int64


In [30]:
a = np.array(range(0,16),float)
a.shape=(4,4)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
----------------
Dimension= 2
Shape= (4, 4)
Size= 16
Internal DT= float64


In [31]:
a.shape=(8,2)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]]
----------------
Dimension= 2
Shape= (8, 2)
Size= 16
Internal DT= float64


In [32]:
a.shape=(16,)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
----------------
Dimension= 1
Shape= (16,)
Size= 16
Internal DT= float64


In [33]:
a.reshape(4,4)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [34]:
a.reshape(2,8)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [35]:
a = a.reshape(4,4)
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [36]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [37]:
a = a.reshape(16,)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
----------------
Dimension= 1
Shape= (16,)
Size= 16
Internal DT= float64


In [38]:
a = a.reshape(2,2,4)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
----------------
Dimension= 3
Shape= (2, 2, 4)
Size= 16
Internal DT= float64


# 2) arange()
## arange() is used for generating range of values with equal interval of values.
## syntax: varname = numpy.arange(start)
## syntax: varname = numpy.arange(start,stop)
## syntax: varname = numpy.arange(start,stop,step)
## arange() by default creates an object of ndarray with 1D array only.
## To build 2D and ND arrays from arange() function, we use reshape() or shape() attribute.

In [39]:
a = np.arange(10)
print(a,type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [40]:
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

----------------
Dimension= 1
Shape= (10,)
Size= 10
Internal DT= int64


In [41]:
a.shape = (2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
a.reshape(5,2)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
a = np.arange(10,22)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (12,)
Size= 12
Internal DT= int64


In [45]:
a.shape = (4,3)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
----------------
Dimension= 2
Shape= (4, 3)
Size= 12
Internal DT= int64


In [46]:
a = np.arange(10,22).reshape(2,3,2)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]]
----------------
Dimension= 3
Shape= (2, 3, 2)
Size= 12
Internal DT= int64


In [47]:
a = np.arange(10,106,5).reshape(5,4)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[ 10  15  20  25]
 [ 30  35  40  45]
 [ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]]
----------------
Dimension= 2
Shape= (5, 4)
Size= 20
Internal DT= int64


In [50]:
a = np.arange(10,106,5).reshape(2,5,2)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[ 10  15]
  [ 20  25]
  [ 30  35]
  [ 40  45]
  [ 50  55]]

 [[ 60  65]
  [ 70  75]
  [ 80  85]
  [ 90  95]
  [100 105]]]
----------------
Dimension= 3
Shape= (2, 5, 2)
Size= 20
Internal DT= int64


# 3) linspace(): Equally linear generated values
## syntax: numpy.linspace(start,stop,num,endpoint,retstep,dtype)

In [51]:
a = np.linspace(1,2)
print(a,type(a))

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ] <class 'numpy.ndarray'>


In [53]:
a = np.linspace(1,2,num=5)
print(a,type(a))

[1.   1.25 1.5  1.75 2.  ] <class 'numpy.ndarray'>


In [54]:
a = np.linspace(1,2,num=10)
print(a,type(a))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ] <class 'numpy.ndarray'>


In [56]:
a = np.linspace(1,2,num=10,endpoint=False)
print(a,type(a))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9] <class 'numpy.ndarray'>


In [57]:
a = np.linspace(1,2,num=10,endpoint=True)
print(a,type(a))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ] <class 'numpy.ndarray'>


In [58]:
a = np.linspace(1,2,num=10,endpoint=False,retstep=True)
print(a,type(a))

(array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]), np.float64(0.1)) <class 'tuple'>


In [62]:
a = np.linspace(1,2,num=10,endpoint=True,retstep=True)
print(a,type(a))

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]), np.float64(0.1111111111111111)) <class 'tuple'>


# 4)zeros():
## syntax: np.zeros(Shape,dtype)

In [63]:
a = np.zeros(6)
print(a,type(a))

[0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [64]:
a = np.zeros(6,dtype=int)
print(a,type(a))

[0 0 0 0 0 0] <class 'numpy.ndarray'>


In [65]:
a = np.zeros((2,2),dtype=int)
print(a,type(a))

[[0 0]
 [0 0]] <class 'numpy.ndarray'>


In [66]:
a = np.zeros((4,4),dtype=int)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (4, 4)
Size= 16
Internal DT= int64


In [67]:
a = np.zeros((4,4,4),dtype=int)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] <class 'numpy.ndarray'>
----------------
Dimension= 3
Shape= (4, 4, 4)
Size= 64
Internal DT= int64


In [68]:
a = np.zeros((4,4,2,4),dtype=int)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]]]] <class 'numpy.ndarray'>
----------------
Dimension= 4
Shape= (4, 4, 2, 4)
Size= 128
Internal DT= int64


# 5) ones()
## syntax: varname = numpy.ones(shape,dtype)

In [70]:
a = np.ones(4)
print(a,type(a))

[1. 1. 1. 1.] <class 'numpy.ndarray'>


In [71]:
a = np.ones((4,4),dtype=int)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (4, 4)
Size= 16
Internal DT= int64


In [72]:
a = np.zeros((3,4),dtype=int)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (3, 4)
Size= 12
Internal DT= int64


In [73]:
a = np.zeros(6,dtype=int).reshape(2,3)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (2, 3)
Size= 6
Internal DT= int64


# 6) full()
## syntax: varname = np.full(shape,fill_value,dtype)


In [74]:
a = np.full(6,9)
print(a,type(a))

[9 9 9 9 9 9] <class 'numpy.ndarray'>


In [75]:
a = np.full(12,"Vinay").reshape(3,4)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[['Vinay' 'Vinay' 'Vinay' 'Vinay']
 ['Vinay' 'Vinay' 'Vinay' 'Vinay']
 ['Vinay' 'Vinay' 'Vinay' 'Vinay']] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (3, 4)
Size= 12
Internal DT= <U5


In [78]:
a = np.full((2,3),6)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[6 6 6]
 [6 6 6]]
----------------
Dimension= 2
Shape= (2, 3)
Size= 6
Internal DT= int64


In [79]:
a = np.full((3,3,3),10)
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]
----------------
Dimension= 3
Shape= (3, 3, 3)
Size= 27
Internal DT= int64


In [80]:
a = np.full((4,3,2),"Vinnu")
print(a)
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']]

 [['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']]

 [['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']]

 [['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']
  ['Vinnu' 'Vinnu']]]
----------------
Dimension= 3
Shape= (4, 3, 2)
Size= 24
Internal DT= <U5


# 7) identity()
## syntax: varname = np.identity(N,dtype)

In [81]:
a = np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [82]:
a = np.identity(2,dtype=int)
print(a)

[[1 0]
 [0 1]]


In [83]:
a = np.identity(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [85]:
a = np.identity((2,5),dtype=int)
print(a)

TypeError: 'tuple' object cannot be interpreted as an integer

# 8) eye()
## syntax: varname = np.eye(N,M=None,K=0,dtype)

In [86]:
a = np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [87]:
a = np.eye(6,k=-1,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [88]:
a = np.eye(6,k=2,dtype=int)
print(a)

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [89]:
a = np.eye(6,k=-2,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [90]:
a = np.eye(6,k=6,dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [91]:
a = np.eye(5,3,k=2,dtype=int)
print(a)

[[0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [92]:
a = np.eye(5,3,k=1,dtype=int)
print(a)

[[0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [93]:
a = np.eye(5,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]


In [94]:
a = np.eye(3,5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [95]:
a = np.eye(10,10,dtype=int)
print(a)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


# Random Number Generation in Numpy:
- randint() : Generating random int values between the specified values 
- rand() : 
- uniform()
- randm()
- normal()
- shuffle()

In [97]:
import numpy as np

In [99]:
# syntax: randint(low, high=None, size=None, dtype=int)
a = np.random.randint(10)
print(a,type(a))

5 <class 'int'>


In [100]:
a = np.random.randint(15)
print(a,type(a))

9 <class 'int'>


In [101]:
a = np.random.randint(10)
print(a,type(a))

6 <class 'int'>


In [102]:
a = np.random.randint(6)
print(a,type(a))

3 <class 'int'>


In [103]:
a = np.random.randint(10,100)
print(a,type(a))

31 <class 'int'>


In [104]:
a = np.random.randint(100,1000)
print(a,type(a))

719 <class 'int'>


In [105]:
a = np.random.randint(1000,10000)
print(a,type(a))

3697 <class 'int'>


In [106]:
a = np.random.randint(10,20,size=6)
print(a,type(a))

[11 16 15 18 12 11] <class 'numpy.ndarray'>


In [ ]:
a = np.random.randint(10,20,size=6)
print(a,type(a))

In [107]:
a = np.random.randint(10,20,size=6)
print(a,type(a))

[12 14 18 10 10 10] <class 'numpy.ndarray'>


In [108]:
a = np.random.randint(10,20,size=15)
print(a,type(a))

[12 16 19 16 14 16 16 17 19 10 17 18 17 19 11] <class 'numpy.ndarray'>


In [109]:
a = np.random.randint(100,1000,size=6)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[245 761 790 994 969 368] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (6,)
Size= 6
Internal DT= int32


In [110]:
a = np.random.randint(10,20,size=(3,3))
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[12 16 10]
 [15 17 17]
 [13 19 13]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (3, 3)
Size= 9
Internal DT= int32


In [111]:
a = np.random.randint(10,20,size=(10,20))
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[16 12 10 15 17 19 18 14 19 12 17 17 15 17 13 12 16 10 11 17]
 [14 11 15 17 16 11 12 17 12 18 16 12 13 12 10 12 15 10 19 19]
 [10 14 15 13 15 11 18 18 10 16 11 10 11 14 11 11 12 18 14 10]
 [17 17 15 14 15 13 15 10 14 15 14 11 19 14 13 10 12 14 15 18]
 [19 16 18 13 10 13 18 16 11 19 14 16 11 15 19 17 14 19 16 12]
 [14 16 18 15 12 16 11 11 10 12 14 14 16 10 12 15 19 16 19 17]
 [11 11 10 19 16 11 19 19 15 19 16 14 16 18 14 13 11 13 17 19]
 [14 10 18 19 15 12 11 11 14 17 13 15 11 12 11 11 11 15 15 18]
 [19 15 15 19 17 14 14 19 12 13 12 10 19 15 10 13 19 19 14 19]
 [14 13 12 15 17 12 14 17 12 11 11 12 13 18 19 19 19 15 11 11]] <class 'numpy.ndarray'>
----------------
Dimension= 2
Shape= (10, 20)
Size= 200
Internal DT= int32


In [112]:
a = np.random.randint(10,20,size=(3,3,3))
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[18 15 15]
  [15 14 19]
  [18 12 10]]

 [[19 10 17]
  [16 10 10]
  [16 19 11]]

 [[12 14 11]
  [13 16 10]
  [15 14 12]]] <class 'numpy.ndarray'>
----------------
Dimension= 3
Shape= (3, 3, 3)
Size= 27
Internal DT= int32


In [113]:
a = np.random.randint(10,20,size=(2,2,2,2))
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[[[[15 12]
   [11 11]]

  [[17 19]
   [12 10]]]


 [[[18 10]
   [17 13]]

  [[17 15]
   [18 10]]]] <class 'numpy.ndarray'>
----------------
Dimension= 4
Shape= (2, 2, 2, 2)
Size= 16
Internal DT= int32


In [114]:
a = np.random.randint(10,20,dtype=float)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

TypeError: Unsupported dtype dtype('float64') for randint

In [118]:
a = np.random.randint(10,50)
print(a,type(a))

14 <class 'int'>


In [122]:
a = np.random.randint(10,50,size=30)
print(a,type(a))
print("----------------")
print("Dimension=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Internal DT=",a.dtype)

[15 10 22 28 27 42 25 26 39 44 38 38 37 16 13 15 14 46 17 46 11 11 43 32
 40 27 45 35 46 44] <class 'numpy.ndarray'>
----------------
Dimension= 1
Shape= (30,)
Size= 30
Internal DT= int32


In [127]:
import sys
a = np.random.randint(10,50,size=20)
print(a,type(a))
print("----------------")
print("Total Memory space of ndarray a=",sys.getsizeof(a))

[22 41 40 38 13 30 45 34 34 40 32 10 21 30 25 42 21 17 28 30] <class 'numpy.ndarray'>
----------------
Total Memory space of ndarray a= 192


In [130]:
import sys
a = np.random.randint(10,50,size=20,dtype='int8')
print(a,type(a))
print("----------------")
print("Default DT=",a.dtype)
print("Total Memory space of ndarray a=",sys.getsizeof(a))

[36 43 22 27 27 15 33 27 16 44 46 20 28 45 32 41 29 24 27 15] <class 'numpy.ndarray'>
----------------
Default DT= int8
Total Memory space of ndarray a= 132


In [132]:
a = np.random.randint(10,50,size=20,dtype='int8')
print(a,type(a))
print("----------------------------------")
b = a.astype("float")
print(b,type(b))

[17 43 19 33 12 35 12 12 33 35 47 48 43 22 40 36 23 46 46 42] <class 'numpy.ndarray'>
----------------------------------
[17. 43. 19. 33. 12. 35. 12. 12. 33. 35. 47. 48. 43. 22. 40. 36. 23. 46.
 46. 42.] <class 'numpy.ndarray'>


In [133]:
a = np.random.randint(10,50,size=(5,5),dtype='int8')
print(a,type(a))

[[11 46 24 12 45]
 [13 39 45 47 41]
 [28 44 14 37 31]
 [18 45 26 41 25]
 [37 40 19 19 43]] <class 'numpy.ndarray'>


In [134]:
a = np.random.randint(10,50,size=(5,5),dtype='int8')
print(a,type(a))
print("----------------------------------")
b = a.astype("float")
print(b,type(b))

[[19 46 29 11 43]
 [48 10 15 10 45]
 [33 15 46 33 16]
 [18 12 12 25 43]
 [42 11 38 29 46]] <class 'numpy.ndarray'>
----------------------------------
[[19. 46. 29. 11. 43.]
 [48. 10. 15. 10. 45.]
 [33. 15. 46. 33. 16.]
 [18. 12. 12. 25. 43.]
 [42. 11. 38. 29. 46.]] <class 'numpy.ndarray'>


# rand = Generating random integer values between 0.0 to 1.0(uniform distribution)

In [135]:
a = np.random.rand(10)
print(a,type(a))

[0.6406966  0.32135816 0.81817117 0.88347064 0.04819178 0.02263162
 0.2603941  0.01263935 0.79325378 0.73873476] <class 'numpy.ndarray'>


In [136]:
a = np.random.rand()
print(a,type(a))

0.7405807813935819 <class 'float'>


In [137]:
a = np.random.rand()
print(a,type(a))

0.6507768176182154 <class 'float'>


In [138]:
a = np.random.rand(5)
print(a,type(a))

[0.66200622 0.16932635 0.88928617 0.60307024 0.62073766] <class 'numpy.ndarray'>


In [139]:
a = np.random.rand(3,3)
print(a,type(a))

[[0.83336318 0.40897308 0.74468395]
 [0.63085478 0.20375661 0.67880651]
 [0.80863515 0.45595651 0.79291476]] <class 'numpy.ndarray'>


In [140]:
a = np.random.rand(4,4)
print(a,type(a))

[[0.18599848 0.88399124 0.5284798  0.00256928]
 [0.146491   0.16403345 0.43716977 0.1453752 ]
 [0.261038   0.13168134 0.18713286 0.91652826]
 [0.98038414 0.25937571 0.90484816 0.81898506]] <class 'numpy.ndarray'>


In [141]:
a = np.random.rand(2,3,3)
print(a,type(a))

[[[0.14759197 0.51105482 0.34089266]
  [0.10121342 0.22727538 0.97376996]
  [0.31920859 0.20854889 0.64605806]]

 [[0.9736388  0.22409958 0.35405802]
  [0.14029317 0.14479076 0.72411272]
  [0.00308596 0.69450204 0.45277581]]] <class 'numpy.ndarray'>


# uniform(): Generating random integer value between user choice start, stop

In [142]:
a = np.random.uniform()
print(a)

0.38783827712594277


In [143]:
a = np.random.uniform(10)
print(a)

7.661382914717329


In [144]:
a = np.random.uniform(10,20)
print(a)

10.010065372366595


In [145]:
a = np.random.uniform(2,5)
print(a)

3.274145876532163


In [146]:
a = np.random.uniform(10,20,size=20)
print(a)

[17.92131132 14.14278531 17.13590616 19.24218534 12.36111972 11.87804385
 13.6841373  16.32911246 14.57356589 15.92512351 19.891496   11.5063007
 18.68398026 17.81863456 13.96066644 16.66836948 14.97395283 13.47297921
 18.81099174 19.42519427]


In [147]:
a = np.random.uniform(10,20,size=(3,3))
print(a)

[[12.9842285  12.4155715  14.7071866 ]
 [10.99174409 17.63319121 13.37786635]
 [15.61910185 18.56177265 12.15685338]]


In [148]:
a = np.random.uniform(10,20,size=(3,3,3))
print(a)

[[[16.39317774 11.64507101 18.43212872]
  [10.42305028 10.90071017 17.19361819]
  [12.35479905 13.31343109 14.73388847]]

 [[13.15948781 14.82822225 10.10862371]
  [17.96019671 15.55561385 11.40041312]
  [17.2034124  11.52757606 12.61243008]]

 [[17.52894082 15.35119907 12.81000177]
  [16.23439238 13.86997461 13.87312806]
  [18.44453115 11.08326076 12.87794784]]]


# randn(): normal distribution

In [149]:
a = np.random.randn() #single random value
print(a,type(a))

0.7584397166140119 <class 'float'>


In [150]:
a = np.random.randn() 
print(a,type(a))

-1.4280919295233683 <class 'float'>


In [151]:
a = np.random.randn(2,3) 
print(a,type(a))

[[ 1.11115527  0.44469472  0.13681002]
 [ 1.67571682 -0.69601212 -1.55237931]] <class 'numpy.ndarray'>


In [152]:
a = np.random.randn(3,3) 
print(a,type(a))

[[ 0.19659172 -1.6052095  -1.19244082]
 [-0.63130026  1.77395894  1.48410357]
 [ 0.62019765 -0.96642154 -0.43564094]] <class 'numpy.ndarray'>


In [153]:
a = np.random.randn(3,3,3) 
print(a,type(a))

[[[-1.3048475  -0.7684505  -0.22953932]
  [-0.96164689 -0.20382104  0.69748996]
  [ 0.8451782   0.22565222 -1.79984622]]

 [[-0.16067732 -0.65217097  0.83897731]
  [ 1.64827689 -0.52435274  0.94465891]
  [-0.51312678 -1.03741903 -1.42328347]]

 [[-0.86827022 -2.13729479  0.70717101]
  [ 0.01835799 -0.19485353 -0.92963591]
  [ 0.66831536 -0.24782378 -1.17166723]]] <class 'numpy.ndarray'>


# uniform(): 

In [154]:
a = np.random.normal()
print(a,type(a))

0.000997106758269737 <class 'float'>


In [155]:
a = np.random.normal()
print(a,type(a))

-0.12373137053570583 <class 'float'>


In [156]:
a = np.random.normal(10,2, size=6) #Generate multi random value
print(a,type(a))

[ 9.18512696  7.83166249  7.64919027 15.51048146  8.71481203 11.92015338] <class 'numpy.ndarray'>


In [158]:
a = np.random.normal(10,2, size=5) 
print(a)

[10.41850926 10.48045159 12.57857043  9.28092094  6.99213375]


In [159]:
a = np.random.normal(10,2, size=(3,3)) 
print(a)

[[ 9.21332304 10.58564044 10.78760656]
 [10.54096577 11.96635211 11.68709501]
 [10.25245225  8.95298403  8.6869758 ]]


In [160]:
a = np.random.normal(10,2, size=(3,3,3)) 
print(a)

[[[ 7.85692636 11.44321213 13.43290373]
  [10.68516525  8.09189116 11.82295068]
  [ 9.31705398 12.72137635  9.59351227]]

 [[ 9.99328675 10.60913602 13.22044271]
  [ 9.71804022  9.87437961 10.31798757]
  [10.95745845  8.56810149  8.64864305]]

 [[11.23140217  9.98939174 11.21958575]
  [ 9.13025569 10.62423232 10.21616903]
  [ 9.54140082  7.9693027   9.55757994]]]


# shuffle() = reorganize the elements in place only

In [163]:
v = np.array([10,20,30,40])
a = np.random.shuffle(v)
print(v,type(v))

[10 40 20 30] <class 'numpy.ndarray'>


In [164]:
v = np.array([10,20,30,"vinay"])
a = np.random.shuffle(v)
print(v,type(v))

['20' '10' 'vinay' '30'] <class 'numpy.ndarray'>


In [165]:
v = np.array([10,23.5,2+4j,"vinay",True])
a = np.random.shuffle(v)
print(v,type(v))

['vinay' '23.5' '(2+4j)' 'True' '10'] <class 'numpy.ndarray'>


# hstack() & vstack() & dstack()

In [166]:
import numpy as np

In [167]:
a = np.array([10,20,30,40])
b = np.array([100,200,300,400])
c = np.hstack((a,b))
print(c,type(c))

[ 10  20  30  40 100 200 300 400] <class 'numpy.ndarray'>


In [168]:
a = np.array([102,203,320,140])
b = np.array([100,200,300,])
c = np.hstack((a,b))
print(c,type(c))

[102 203 320 140 100 200 300] <class 'numpy.ndarray'>


In [172]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
b = np.array([[200,400],[300,500],[100,600]])
c = np.hstack((a,b))
print(c,type(c))

[[ 10  20  30 200 400]
 [ 40  50  60 300 500]
 [ 70  80  90 100 600]] <class 'numpy.ndarray'>


In [173]:
a = np.array([10,20,30,40])
b = np.array([100,200,300,400])
c = np.vstack((a,b))
print(c,type(c))

[[ 10  20  30  40]
 [100 200 300 400]] <class 'numpy.ndarray'>


In [175]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
b = np.array([[200,400],[300,500],[100,600]])
c = np.vstack((a,b))
print(c,type(c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2