## Indexing is the process of obtaining single value from given iterable object(contains multiple values).
## The values of iterable object contains +ve and -ve indices.
## Now an object of ndarray is also one of the iterable object.
## The element of ndarray contains +ve and -ve indices.
## In NumPy programming, we can apply indexing operation on 3-types of arrays. They are:
- 1) 1-D Indexing
- 2) 2-D Indexing
- 3) N-D Indexing

## 1-D indexing:
## syntax: 1darray[Index]

In [1]:
import numpy as np
a = np.array([10,20,30,40,50,60])
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [2]:
a[2]

np.int64(30)

In [3]:
a[4]

np.int64(50)

In [4]:
a[-1]

np.int64(60)

In [5]:
a[-3]

np.int64(40)

In [6]:
len(a)

6

In [7]:
a[-len(a)]

np.int64(10)

In [ ]:
## 2D-Indexing
## syntax: 2Darray = [rowindex][colindex]

In [9]:
a = np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [10]:
a[1,1]

np.int64(5)

In [11]:
a[3,3]

np.int64(15)

In [12]:
a[1][3]

np.int64(7)

In [13]:
a[-2][-2]

np.int64(10)

In [15]:
a[-2,0]

np.int64(8)

# ND - indexing
## syntax: ndarrayobject[MatrixIndex,RowIndex,ColIndex]
## syntax: ndarrayobject[MatrixIndex],[RowIndex],[ColIndex]

In [16]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [17]:
a[0][0][0]

np.int64(0)

In [20]:
a[2][2][2]

np.int64(26)

In [21]:
a[0,1,1]

np.int64(4)

In [22]:
a[-1]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

# NumPy-Slicing

## The process of obtaining range of values or sub-values from an iterable object is called Slicing.
## We can apply slicing operation on 3-types of ndarray. they are
- 1-D array
- 2-D array
- N-D array

## 1D array:
## syntax: 1darray[Begin:End]
## 1darray[Begin:]
## 1darray[:End] 
## 1darray[Begin:End:step]
## 1darray[:]

In [23]:
a = np.array([10,20,30,40,50,60,70,80,90,15,25,35])
print(a,type(a))

[10 20 30 40 50 60 70 80 90 15 25 35] <class 'numpy.ndarray'>


In [24]:
a[0:4]

array([10, 20, 30, 40])

In [25]:
a[4:9]

array([50, 60, 70, 80, 90])

In [26]:
a[-4:-1]

array([90, 15, 25])

In [27]:
a[4:]

array([50, 60, 70, 80, 90, 15, 25, 35])

In [28]:
a[9:]

array([15, 25, 35])

In [29]:
a[:5]

array([10, 20, 30, 40, 50])

In [31]:
a[:-5]

array([10, 20, 30, 40, 50, 60, 70])

In [32]:
a[1:12:2]

array([20, 40, 60, 80, 15, 35])

In [33]:
a[::]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [34]:
a[1::2]

array([20, 40, 60, 80, 15, 35])

## 2D-array
## syntax: 2darray[RowBegin:RowEnd:RowStep,ColBegin:ColEnd:ColumnStep]

In [35]:
import numpy as np

In [36]:
a = np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [37]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [38]:
a[:,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [41]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [42]:
a[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a[0:4:3,0:4:3]

array([[ 0,  3],
       [12, 15]])

## ND-slicing
## Ndarray[MatrixBegin:ME:MS,RowBegin:RE:RS, ColBegin:ColEnd:Colstep]

In [44]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [45]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [46]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [47]:
a[0][1]

array([3, 4, 5])

In [48]:
a[1][2]

array([15, 16, 17])

In [49]:
a[2][2]

array([24, 25, 26])

In [50]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [51]:
a[0:2,0:1,0:2]

array([[[ 0,  1]],

       [[ 9, 10]]])