# NumPy Indexing
## Indexing is the process of obtaining single value from given iterable object.(Contains multiple values)
## The values of iterable object contains positive indices 0,1,2,......,len-1) and negative indices.
## Now, an object if ndarray is also one of the iterable object.
## The element of ndarray contains +ve and -ve index.
## In numpy program, we can apply indexing operation on 3-types of array. They are
### 1) 1-D array
### 2) 2-D array
### 3) 3-D array

# 1-D Indexing

## syntax: 1 ndarray[index]
### Here 1 ndarray is an object of class
### Index can be +ve or =ve

In [2]:
import numpy as np

In [3]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [4]:
a[0]

np.int64(10)

In [5]:
a[1]

np.int64(20)

In [6]:
a[4]

np.int64(50)

In [7]:
b = np.array([30,40,50,60,70,80,90])
print(b,type(b))

[30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [8]:
b[3]

np.int64(60)

In [9]:
b[6]

np.int64(90)

In [10]:
b[4]

np.int64(70)

In [11]:
b[2]

np.int64(50)

In [12]:
b[1]

np.int64(40)

# 2-D Indexing

In [13]:
a = np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [14]:
a[2]

array([ 8,  9, 10, 11])

In [15]:
a[3]

array([12, 13, 14, 15])

In [16]:
a[1]

array([4, 5, 6, 7])

In [17]:
a[0]

array([0, 1, 2, 3])

In [18]:
a[2,1]

np.int64(9)

In [19]:
a[1,3]

np.int64(7)

In [20]:
a[3,3]

np.int64(15)

In [23]:
a[0,3]

np.int64(3)

In [24]:
a[3,1]

np.int64(13)

In [25]:
a[-4,-4]

np.int64(0)

In [26]:
a[-4,-3]

np.int64(1)

In [27]:
a[-3][-2]

np.int64(6)

In [28]:
a[-2][-3]

np.int64(9)

# 3-D Indexing

In [29]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [30]:
a[2,2,1]

np.int64(25)

In [31]:
a[0,2,2]

np.int64(8)

In [32]:
a[0,1,2]

np.int64(5)

In [33]:
a[0,0,2]

np.int64(2)

In [35]:
a[1,0,2]

np.int64(11)

In [36]:
a[1,1,2]

np.int64(14)

In [37]:
a[2,0,2]

np.int64(20)

# NumPy Slicing

## The process of obtaining range of value (or) sub values from an iterable object.
## We can apply slicing operation on 3-types of ndarray.they are:
### 1) 1-D array
### 2) 2-D array
### 3) 3-D array

## 1-D array
### syntax: 
### 1darray[Begin:End] = It gives range of value from begin index to end index(-1) provided.
### 1darray[Begin:] = It gives range of value from begin index to last value.
### 1darray[:End] = It gives range of value from first value to end -1 index.
### 1darray[:] = It gives complete values of 1darray (or) first value to last value of 1darray.
### 1darray[start:stop:step]

In [38]:
a = np.array([10,20,30,40,50,60,70,15,25,35])
print(a,type(a),id(a))

[10 20 30 40 50 60 70 15 25 35] <class 'numpy.ndarray'> 1205101076688


In [39]:
a[1:6]

array([20, 30, 40, 50, 60])

In [40]:
a[0:8]

array([10, 20, 30, 40, 50, 60, 70, 15])

In [41]:
a[2:7]

array([30, 40, 50, 60, 70])

In [42]:
a[3:9]

array([40, 50, 60, 70, 15, 25])

In [43]:
a[4:10]

array([50, 60, 70, 15, 25, 35])

In [44]:
a[5:]

array([60, 70, 15, 25, 35])

In [45]:
a[3:]

array([40, 50, 60, 70, 15, 25, 35])

In [46]:
a[7:]

array([15, 25, 35])

In [47]:
a[:8]

array([10, 20, 30, 40, 50, 60, 70, 15])

In [48]:
a[:6]

array([10, 20, 30, 40, 50, 60])

In [49]:
a[:9]

array([10, 20, 30, 40, 50, 60, 70, 15, 25])

In [50]:
a[:]

array([10, 20, 30, 40, 50, 60, 70, 15, 25, 35])

In [51]:
a[1:9:2]

array([20, 40, 60, 15])

In [52]:
a[1:9:3]

array([20, 50, 15])

# 2-D array
## Syntax: 
## 2Darray[RowBegin:RowEnd,RowStep,ColBegin:ColEnd:ColStep]

In [54]:
a = np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [55]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [56]:
a[:,0:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [57]:
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [58]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [59]:
a[0:4:2,0:4]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [60]:
a[::2,::]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

## Here Row, column represents either positive (or) negative
## Its not possible to get principle diagonal elements by using regular indexing and slicing operations.

# N-D array

## syntax: NDarray[MateixBegin:End:Step,RowBegin:End:Step,ColBegin:End:Step]
### Here Matrix Begin, End represents either positive or negative index.

In [62]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [63]:
a[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [65]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [66]:
a[0:1]

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [67]:
a[0][1]

array([3, 4, 5])

In [68]:
a[0:3]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
a[0][2]

array([6, 7, 8])

In [71]:
print(a[0:2,0:1,0:2])

[[[ 0  1]]

 [[ 9 10]]]


## With slicing operations, we can't get random elements.
## For getting random elements, we must learn advance indexing & slicing