In [1]:
import numpy as np

In [3]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
a.shape=(9,)

In [7]:
print(a)

[10 20 30 40 50 60 70 80 90]


# Today my requirement is multiples of 3

In [10]:
ba =a%3==0
print(ba,type(ba))

[False False  True False False  True False False  True] <class 'numpy.ndarray'>


In [11]:
ba = a%5==0
print(ba)

[ True  True  True  True  True  True  True  True  True]


In [13]:
# pass boolean to ndarray object
a[ba]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
# get the multiples of 3
a[a%3==0]

array([30, 60, 90])

In [15]:
# get the multiples of 4
a[a%4==0]

array([20, 40, 60, 80])

In [16]:
# get the multiples of 5
a[a%5==0]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
a = np.array([[10,-20,-30],[-40,50,-60],[-70,-80,90]])
print(a)

[[ 10 -20 -30]
 [-40  50 -60]
 [-70 -80  90]]


In [20]:
# get all +ve numbers
pa = a[a>0] 
print(pa,type(pa))

[10 50 90] <class 'numpy.ndarray'>


In [21]:
#Get all -ve numbers
pa = a[a<0]
print(pa,type(pa))

[-20 -30 -40 -60 -70 -80] <class 'numpy.ndarray'>


# copy() vs view()

In [22]:
import numpy as np

In [23]:
a = np.array([20,30,40,50])
print(a,type(a))

[20 30 40 50] <class 'numpy.ndarray'>


In [24]:
b = a.copy()
print(b,type(b))

[20 30 40 50] <class 'numpy.ndarray'>


In [25]:
a[0]

np.int64(20)

In [26]:
b[0]

np.int64(20)

In [27]:
a[0]=100 # modified original array

In [28]:
print(a)

[100  30  40  50]


In [29]:
print(b)

[20 30 40 50]


In [30]:
b[0]=200 # copied array modified
print(b)

[200  30  40  50]


# view()

In [31]:
a = np.array([20,30,40,50])
print(a,type(a))

[20 30 40 50] <class 'numpy.ndarray'>


In [32]:
b=a.view()
print(b)

[20 30 40 50]


In [33]:
a[0]=100 # original array modified it will reflect dup copy as well
print(a)

[100  30  40  50]


In [34]:
print(b)

[100  30  40  50]


In [35]:
a = np.array([20,30,40,50])
print(a,type(a))
b = a.copy()
print(a,a.base)
print(b,b.base)

[20 30 40 50] <class 'numpy.ndarray'>
[20 30 40 50] None
[20 30 40 50] None


In [36]:
a = np.array([20,30,40,50])
print(a,type(a))
b = a.view()
print(a,a.base)
print(b,b.base)

[20 30 40 50] <class 'numpy.ndarray'>
[20 30 40 50] None
[20 30 40 50] [20 30 40 50]
