# NumPy Indexing:
## Indexing is the process of obtaining single value from given iterable object(It contains multiple values)
## The values of iterable object contains +ve and -ve indices.
## Now an object of ndarray is also one of the iterable object.
## The element of ndarray contains -ve and +ve indices.
## In numpy programming , we can apply indexing operations on 3-types.
### 1) 1-D
### SYNTAX: 1darray[index]
### 2) 2-D
### SYNTAX: 2darrayobj[row-ind,col-ind]
### 3) 3-D

 # 1-D Indexing

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50,60])
print(a,type(a))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [3]:
a[0] # 10

np.int64(10)

In [4]:
a[1] # 20

np.int64(20)

In [5]:
a[2] # 30

np.int64(30)

In [8]:
a[len(a)-1] # 60

np.int64(60)

In [9]:
a[-len(a)] # 10

np.int64(10)

In [10]:
a[-1]

np.int64(60)

In [11]:
a[-4]

np.int64(30)

In [12]:
a[100] # IndexError: index 100 is out of bounds for axis 0 with size 6

IndexError: index 100 is out of bounds for axis 0 with size 6

In [14]:
a[-100] #IndexError: index -100 is out of bounds for axis 0 with size 6

IndexError: index -100 is out of bounds for axis 0 with size 6

In [17]:
print("Content of a=",a)
print("Dimensions=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)

Content of a= [10 20 30 40 50 60]
Dimensions= 1
Shape= (6,)
Size= 6


In [18]:
print("Item size of a=",a.itemsize) # here itemsize gives us size of the each value(bytes)

Item size of a= 8


In [19]:
a = np.array([1.0,2.0,3.0,4.0,5.0,6.0])
print(a,type(a))
print("-------------------------------")
print("Content of a=",a)
print("Dimensions=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Item size of a=",a.itemsize) # here itemsize gives us size of the each value(bytes)

[1. 2. 3. 4. 5. 6.] <class 'numpy.ndarray'>
-------------------------------
Content of a= [1. 2. 3. 4. 5. 6.]
Dimensions= 1
Shape= (6,)
Size= 6
Item size of a= 8


# 2D Indexing

In [20]:
a = np.arange(16).reshape(4,4)
print(a,type(a))
print("----------------------------")
a[1,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
----------------------------


np.int64(5)

In [21]:
a[3,3] # 15

np.int64(15)

In [22]:
a[3,1] # 13

np.int64(13)

In [23]:
a[1,3] # 7

np.int64(7)

In [24]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
a[-4,-4]

np.int64(0)

In [26]:
a[-3,-2]

np.int64(6)

In [27]:
a[-2,-2]

np.int64(10)

In [28]:
a[1,-2]

np.int64(6)

In [29]:
a[2,-3]

np.int64(9)

# ND -Indexing

In [30]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))
print("--------------------------")
print("Content of a=",a)
print("Dimensions=",a.ndim)
print("Shape=",a.shape)
print("Size=",a.size)
print("Item size of a=",a.itemsize) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>
--------------------------
Content of a= [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimensions= 3
Shape= (3, 3, 3)
Size= 27
Item size of a= 8


In [31]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [32]:
a[0,1,1] # Matrix,row index, col index = 4

np.int64(4)

In [33]:
a[0,2,2] # 8 

np.int64(8)

In [34]:
a[1,0,2] # 11

np.int64(11)

In [35]:
a[1,2,0] # 15

np.int64(15)

In [36]:
a[2,0,2] # 20

np.int64(20)

In [37]:
a[2,2,2] # 26

np.int64(26)

In [38]:
a[-3,1,1]

np.int64(4)

In [39]:
a[-2,1,1]

np.int64(13)

In [40]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [41]:
a[-2]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
a[-1]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

# Slicing operations
## The process of obtaining range of values or sub values from an iterable object is called "Slicing"
## We can apply Slicing operation on 3 types if ndarray.
### 1D ARRAY
### Syntax: 1darray[Begin:End]
### Syntax: 1darray[Begin:]
### Syntax: 1darray[:End]
### Syntax: 1darray[:]
### Syntax: 1darray[Begin:End:step]
## Here Begin, end, step can be either +ve or -ve 
### 2D ARRAY
### Syntax:
### 3D ARRAY
### Syntax:

In [43]:
a = np.array([10,20,30,40,50,60,70,80,90,15,25,35])
print(a,type(a))

[10 20 30 40 50 60 70 80 90 15 25 35] <class 'numpy.ndarray'>


In [44]:
a[0:4] # 10 20 30 40

array([10, 20, 30, 40])

In [45]:
a[1:6] # 20 30 40 50 60

array([20, 30, 40, 50, 60])

In [46]:
a[-12:-4]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [47]:
a[-9:-2]

array([40, 50, 60, 70, 80, 90, 15])

In [48]:
a[10:3]

array([], dtype=int64)

In [49]:
a[-2:-10]

array([], dtype=int64)

In [50]:
a[4:]

array([50, 60, 70, 80, 90, 15, 25, 35])

In [51]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [52]:
a[-4:]

array([90, 15, 25, 35])

In [53]:
a[:-3]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
a[:5]

array([10, 20, 30, 40, 50])

In [55]:
print(a)

[10 20 30 40 50 60 70 80 90 15 25 35]


In [56]:
a[1:9:2]

array([20, 40, 60, 80])

In [57]:
a[0:12:2]

array([10, 30, 50, 70, 90, 25])

In [58]:
a[::]

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35])

In [59]:
a[::2]

array([10, 30, 50, 70, 90, 25])

In [60]:
a[1::2]

array([20, 40, 60, 80, 15, 35])

In [61]:
a[::-1]

array([35, 25, 15, 90, 80, 70, 60, 50, 40, 30, 20, 10])

In [62]:
a[::-2]

array([35, 15, 80, 60, 40, 20])

In [63]:
a[::-3]

array([35, 90, 60, 30])

# 2D slice

In [64]:
import numpy as np

In [66]:
a = np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [67]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [68]:
a[::1,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [69]:
a[1:3,:2]

array([[4, 5],
       [8, 9]])

In [70]:
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [71]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [72]:
a[1:,1::]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [73]:
a[1:3,::]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a[0:4:2,0:4]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [75]:
a[-2:,-2:]

array([[10, 11],
       [14, 15]])

In [76]:
a[-4:,-3:-1]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [77]:
a[::3,::3]

array([[ 0,  3],
       [12, 15]])

In [78]:
a[0:4:3,0:4:3]

array([[ 0,  3],
       [12, 15]])

In [80]:
a[1::2,:3:2]

array([[ 4,  6],
       [12, 14]])

# ND slicing

In [82]:
a = np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [83]:
a[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [85]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [86]:
a[0:3]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
a[0,0]

array([0, 1, 2])

In [91]:
a[0,1]

array([3, 4, 5])

In [92]:
a[0,2]

array([6, 7, 8])

In [93]:
a[1,0]

array([ 9, 10, 11])

In [94]:
a[1,1]

array([12, 13, 14])

In [95]:
a[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
a[0:2,0:1,0:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [97]:
 a[-3:-1,-3:-2,-3:-1]

array([[[ 0,  1]],

       [[ 9, 10]]])

# advanced indexing & slicing on 1D 2D ND

In [100]:
ind = np.array([10,20,30,40,50,60,70,80,90])
print(ind,type(ind))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [101]:
# We want to get 10 80 90 (nothing but randon elements)
ind=np.array([0,7,8]) # [0:-2,-1]
a[ind]

array([10, 80, 90])

In [103]:
ind = np.array([0,-2,-1])
a[ind]

array([10, 80, 90])