## The array splitting in numpy is like a slice of cake.
## Think of each element in numpy array as a slice of cake.
## Splitting divide the cake into smaller slices often along specific dimensions or based on certain cretiria.
## we can split horizontal, vertical or even diagonally depending on our needs.
## The split() , v&h&d split() functions are important tools for dividing arrays along various axes and dimensional.
## These functions are particularly useful  when working with one-dimensional array, matrices (or) high dimensional datasets.
### split()
### array_split()
### hsplit()
### vsplit()
### dsplit()

# a) split()

In [2]:
import numpy as np
a = np.arange(6)
print(a,type(a))
print("------------------")
b = np.split(a,2) # Here 2 is how many splits we want
print(b,type(b))

[0 1 2 3 4 5] <class 'numpy.ndarray'>
------------------
[array([0, 1, 2]), array([3, 4, 5])] <class 'list'>


In [3]:
import numpy as np
a = np.arange(10)
print(a,type(a))
print("------------------")
b = np.split(a,5) # Here 2 is how many splits we want
print(b,type(b))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
------------------
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


In [4]:
for val in b:
    print(val,type(val))

[0 1] <class 'numpy.ndarray'>
[2 3] <class 'numpy.ndarray'>
[4 5] <class 'numpy.ndarray'>
[6 7] <class 'numpy.ndarray'>
[8 9] <class 'numpy.ndarray'>


In [5]:
a = np.arange(8)
print(a,type(a))
print("-------------------")
b = np.split(a,[3,5,6,10]) # Here it will split accordingly indexes
print(b,type(b))

[0 1 2 3 4 5 6 7] <class 'numpy.ndarray'>
-------------------
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7]), array([], dtype=int64)] <class 'list'>


In [6]:
b = np.split(a,4)
print(b,type(b))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])] <class 'list'>


# b) array_split()

In [8]:
a = np.arange(13)
print(a,type(a))
print("---------------------------")
b = np.array_split(a,5)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
---------------------------
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10]), array([11, 12])] <class 'list'>


In [9]:
a = np.arange(13)
print(a,type(a))
print("---------------------------")
b = np.array_split(a,[4,5,7,9])
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
---------------------------
[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8]), array([ 9, 10, 11, 12])] <class 'list'>


In [10]:
a = np.arange(13)
print(a,type(a))
print("---------------------------")
b = np.array_split(a,[8,12])
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
---------------------------
[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12])] <class 'list'>


# Splitting NumPy 2D arrays

In [11]:
array = np.array([[3,2,1],[8,9,7],[4,6,5]])
print(array)

[[3 2 1]
 [8 9 7]
 [4 6 5]]


In [14]:
import numpy as np
array = np.array([[3,2,1],[8,9,7],[4,6,5]])
result = np.split(array,3,axis=1) # 
print("2D array")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)

2D array
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [ ]:
import numpy as np
array = np.array([[3,2,1],[8,9,7],[4,6,5]])
result = np.split(array,3,axis=0) # 
print("2D array")
print(array)
print("\nResult after numpy.split() along axis=0:")
print(result)

# Vsplit()

In [17]:
Matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
result = np.vsplit(Matrix,2)
print("Matrix:")
print(Matrix)
print("------------------------------")
print("\nResult after numpy.vsplit() along:")
print(result)

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------------

Result after numpy.vsplit() along:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [18]:
x = np.arange(8.0).reshape(2,2,2)
print(x)
print("--------------")
z = np.vsplit(x,2)
print(z)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
--------------
[array([[[0., 1.],
        [2., 3.]]]), array([[[4., 5.],
        [6., 7.]]])]


# hsplit()

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a,type(a))
print("------------------------------------")
result = np.hsplit(a,2)
print("2D array")
print(a)
print("\nResult after numpy.hsplit() along:")
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'>
------------------------------------
2D array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after numpy.hsplit() along:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [20]:
x = np.arange(8.0).reshape(2,2,2)
print(x)
print("--------------")
z = np.hsplit(x,2)
print(z)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
--------------
[array([[[0., 1.]],

       [[4., 5.]]]), array([[[2., 3.]],

       [[6., 7.]]])]


# dsplit() -- 3D onwords

In [21]:
import numpy as np
original_3d_array = np.arange(24).reshape((2,3,4))
result = np.dsplit(original_3d_array,2)

print("Original 3D array:")
print(original_3d_array)
print("\nResult after numpy.dsplit():")
print(result)

Original 3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result after numpy.dsplit():
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
