## Array splitting in numpy like a slice of cake.
## Think of each element in NumPy array as a slice of cake.
## Splitting divides the cake into smaller chunks.
## We can split horizontally, vertically or even diagonally depending on our needs.
- split()
- array_split()
- hsplit()
- vsplit()
- dsplit()

# split()

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
print(a)
print("-------------------")
b = np.split(a,2)
print(b,type(b))

[0 1 2 3 4 5]
-------------------
[array([0, 1, 2]), array([3, 4, 5])] <class 'list'>


In [3]:
a = np.arange(6)
print(a)
print("-------------------")
b = np.split(a,3)
print(b,type(b))

[0 1 2 3 4 5]
-------------------
[array([0, 1]), array([2, 3]), array([4, 5])] <class 'list'>


In [4]:
a = np.arange(10)
print(a)
print("-------------------")
b = np.split(a,2)
print(b,type(b))

[0 1 2 3 4 5 6 7 8 9]
-------------------
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])] <class 'list'>


In [5]:
a = np.arange(10)
print(a)
print("-------------------")
b = np.split(a,5)
print(b,type(b))

[0 1 2 3 4 5 6 7 8 9]
-------------------
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


In [6]:
for val in b:
    print(val,type(val))

[0 1] <class 'numpy.ndarray'>
[2 3] <class 'numpy.ndarray'>
[4 5] <class 'numpy.ndarray'>
[6 7] <class 'numpy.ndarray'>
[8 9] <class 'numpy.ndarray'>


In [7]:
a = np.arange(8)
b = np.split(a,[3,5,6,10])
print(b)

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7]), array([], dtype=int64)]


# array_split()

In [8]:
a = np.arange(15)
print(a)
print("-------------------")
b = np.array_split(a,3)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------------
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])] <class 'list'>


In [9]:
a = np.arange(9)
print(a)
print("-------------------")
b = np.array_split(a,5)
print(b,type(b))

[0 1 2 3 4 5 6 7 8]
-------------------
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8])] <class 'list'>


In [10]:
a = np.arange(10)
print(a)
print("-------------------")
b = np.array_split(a,4)
print(b,type(b))

[0 1 2 3 4 5 6 7 8 9]
-------------------
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


In [11]:
a = np.arange(13)
print(a)
print("-------------------")
b = np.array_split(a,[4,5,7,9])
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
-------------------
[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8]), array([ 9, 10, 11, 12])] <class 'list'>


# split()

In [12]:
a = np.array([[3,2,1],[8,9,7],[4,5,6]])
b = np.split(a,3,axis=1)
print(a)

[[3 2 1]
 [8 9 7]
 [4 5 6]]


In [13]:
a = np.array([[3,2,1],[8,9,7],[4,5,6]])
b = np.split(a,3,axis=0)
print(a)

[[3 2 1]
 [8 9 7]
 [4 5 6]]


In [14]:
a = np.array([[3,2,1],[8,9,7],[4,5,6]])
b = np.split(a,3,axis=1)
print(a)

[[3 2 1]
 [8 9 7]
 [4 5 6]]


# vsplit()

In [15]:
a = np.array([[3,2,1],[8,9,7],[4,5,6]])
b = np.vsplit(a,3)
print(a)

[[3 2 1]
 [8 9 7]
 [4 5 6]]


# hsplit()

In [16]:
a = np.array([[3,2,1,0],[8,1,9,7],[4,4,5,6]])
b = np.hsplit(a,2)
print(a)

[[3 2 1 0]
 [8 1 9 7]
 [4 4 5 6]]


In [17]:
a = np.array([[3,2,1],[1,9,7],[4,5,6]])
b = np.hsplit(a,3)
print(a)

[[3 2 1]
 [1 9 7]
 [4 5 6]]


# dsplit()

In [18]:
a = np.arange(24).reshape((2,3,4))
b = np.dsplit(a,2)
print(b,type(b))

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])] <class 'list'>
