# SPLITTING THE NDARRAY OBJECT
## In NumPy, splitting an ndarray means dividing it into multiple sub-arrays. This is useful when you want to break data into chunks for processing, training, or analysis.
## There are few types:
### a) split() ----> Equal parts
### b) array_split() ---->Equal / unequal parts
### c) hsplit()  ----> Splits horizontally (columns) for 2D arrays
### d) vsplit() ----> Splits vertically (rows) for 2D arrays
### e) dsplit()

# split()
## Array splitting NumPy is like a slice of cake.
## Think of each element in a numpy array as a slice of cake.
## We can split horizontal, vertical (or) even diagonally depends upon our needs.
## The split(), hsplit(), vsplit() and dsplit() functions are important tools for dividing arrays along various axis and dimensions.
## These functions are particularly useful when working with one dimensional arrays, matrices (or) high dimensional data sets.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
array = np.array_split(arr,3)
print(array,type(array))

[array([1, 2]), array([3, 4]), array([5])] <class 'list'>


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
array = np.array_split(arr,4)
print(array,type(array))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])] <class 'list'>


# Splitting arrays into equal parts using numpy.split()
## It is a function that divides an array into equal parts along a specified axis.
## The code imports numpy to create an array of num(0-10), then splits it in half(horizontal) using numpy.split()

In [5]:
import numpy as np

In [12]:
a = np.arange(10)
print(a,type(a))
print("----------------------")
b = np.split(a,5)
print(b,type(b))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
----------------------
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


In [11]:
a = np.arange(12)
print(a,type(a))
print("----------------------")
b = np.split(a,2)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
----------------------
[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])] <class 'list'>


# array_split()
## It is a function splitting into equal (or) unequal sub arrays (or) is similar to numpy.split() but it allows for uneven splitting of arrays.
## This is useful when the array cannot be evenly divided by the specified number of splits. 

In [13]:
import numpy as np

In [15]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,2)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])] <class 'list'>


In [16]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,4)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])] <class 'list'>


In [17]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,6)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])] <class 'list'>


In [18]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,8)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10]), array([11]), array([12])] <class 'list'>


In [19]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,13)
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0]), array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10]), array([11]), array([12])] <class 'list'>


In [20]:
a = np.arange(13)
print(a,type(a))
print("----------------------------------------------------")
b = np.array_split(a,[4,5,7,9])
print(b,type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
----------------------------------------------------
[array([0, 1, 2, 3]), array([4]), array([5, 6]), array([7, 8]), array([ 9, 10, 11, 12])] <class 'list'>
